-- Generated by scripts/build-authored.py — do not edit; edit authoring/ instead.
DELETE FROM lesson_blocks WHERE lesson_id = '001';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.01', '001', 1, 'goal', 'Sau bài này bạn làm được gì', 'Đọc một đề case dài một trang và viết lại thành **problem statement ba dòng**: câu hỏi chính phải trả lời, tiêu chí biết là đã trả lời xong, và người ra quyết định là ai.

Không thuộc bài này: giải case, dựng issue tree, tính toán. Ở đây chỉ làm đúng một việc — **xác định câu hỏi**. Việc này chiếm chưa tới 5% thời gian làm case nhưng quyết định 100% phần còn lại đi đúng hay đi lạc.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.02', '001', 2, 'concept', 'Đề bài viết ra và câu hỏi thật sự hiếm khi trùng nhau', 'Đề case luôn được viết dưới góc nhìn của người trong cuộc, và người trong cuộc thường đã tự chẩn đoán sẵn. "Chúng tôi muốn biết nên mở thêm bao nhiêu cửa hàng" là một *giải pháp đã chọn*, không phải câu hỏi. Câu hỏi thật sự có thể là "mô hình cửa hàng hiện tại có đủ lành để nhân rộng không".

Ba dấu hiệu đề bài đang giấu câu hỏi thật:

- **Đề hỏi "làm thế nào" khi chưa ai trả lời "có nên không".** Hỏi mở ở đâu trong khi 4/12 cửa hàng đang lỗ là bỏ qua một bước.
- **Đề nêu một mục tiêu không có số.** "Tăng trưởng mạnh hơn" không kiểm chứng được, nên không trả lời được.
- **Đề đưa sẵn nguyên nhân.** "Doanh thu giảm vì đối thủ giảm giá" — đó là giả thuyết của khách hàng, phải kiểm chứ không phải nhận.

Việc của bạn không phải là bắt bẻ đề bài. Việc của bạn là **nói lại câu hỏi bằng ngôn ngữ kiểm chứng được**, rồi xác nhận với người ra quyết định trước khi phân tích.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.03', '001', 3, 'concept', 'Ba dòng của một problem statement', 'Dòng 1 — **Câu hỏi quyết định**: một câu, có động từ quyết định (có nên, chọn cái nào, bao nhiêu), có đối tượng cụ thể, có mốc thời gian.

Dòng 2 — **Tiêu chí thành công**: con số nào, đạt mức nào, trong bao lâu. Không có số ở dòng này thì cả bài không có đích.

Dòng 3 — **Người quyết định và ràng buộc**: ai sẽ dùng câu trả lời này, và họ bị chặn bởi cái gì (ngân sách, thời gian, năng lực, quy định).

Ba dòng, không hơn. Nếu bạn cần dòng thứ tư, gần như chắc chắn bạn đang viết phần phân tích chứ không còn viết đề nữa.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.04', '001', 4, 'worked_example', 'Từ một trang đề thành ba dòng', '**Đề (rút gọn):** Một chuỗi phòng tập 8 cơ sở tại TP.HCM, doanh thu ba năm đi ngang quanh 60 tỷ. Ban giám đốc thấy các chuỗi mới mở rất nhanh nên muốn biết "nên mở thêm bao nhiêu cơ sở trong 18 tháng tới và ở quận nào". Họ nói thêm: hai cơ sở mới nhất mở năm ngoái hiện chưa hoà vốn, và tỷ lệ hội viên bỏ tập sau 3 tháng là 45%.

**Bước 1 — gạch chân các dữ kiện không khớp với câu hỏi.** Hai cơ sở mới chưa hoà vốn; bỏ tập 45%. Cả hai đều nói rằng mô hình hiện tại đang rò rỉ. Mở thêm chỉ nhân bản chỗ rò rỉ đó.

**Bước 2 — hỏi "nếu trả lời đúng câu hỏi trong đề, ban giám đốc có ra quyết định tốt hơn không?"** Không. Họ sẽ mở thêm 5 cơ sở cùng kiểu và mất tiền nhanh hơn.

**Bước 3 — viết lại thành ba dòng:**

> **Câu hỏi:** Chuỗi có nên mở thêm cơ sở trong 18 tháng tới không, và nếu có thì điều kiện nào phải đạt trước khi mở cơ sở đầu tiên?
>
> **Tiêu chí thành công:** một cơ sở đạt hoà vốn trong vòng 9 tháng và giữ tỷ lệ bỏ tập sau 3 tháng dưới 30%; nếu hai điều kiện này chưa đạt ở các cơ sở hiện có thì câu trả lời là chưa mở.
>
> **Người quyết định và ràng buộc:** ban giám đốc, ngân sách đầu tư tối đa 20 tỷ trong 18 tháng, không tăng vay.

**Bước 4 — kiểm lại bằng ba câu hỏi:** Câu hỏi có động từ quyết định chưa? Có. Tiêu chí có số chưa? Có. Có nói ai quyết định chưa? Có.

Chú ý: bản viết lại **không** bác bỏ đề bài. Nó vẫn trả lời "mở bao nhiêu", chỉ đặt thêm điều kiện phải qua trước. Đó là cách định khung lại mà không biến mình thành người khó chịu trong phòng họp.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.05', '001', 5, 'pitfall', 'Bốn kiểu hỏng của problem statement', '**FRM-01 — nhắc lại đề thay vì định khung.** Viết "Chuỗi muốn biết nên mở thêm bao nhiêu cơ sở" là chép lại. Dấu hiệu: bỏ problem statement của bạn đi thì bài chẳng mất gì. Sửa: mỗi dòng phải thêm một thông tin không có trong đề — điều kiện, con số, ràng buộc.

**FRM-02 — mục tiêu không có số.** "Cải thiện lợi nhuận" không phải tiêu chí. Sửa: luôn có một con số và một mốc thời gian, kể cả khi con số đó là giả định của bạn — ghi rõ là giả định.

**FRM-04 — nhảy vào giải pháp ngay câu đầu.** "Chuỗi nên tập trung vào khách hàng doanh nghiệp" là kết luận, mà bạn chưa phân tích gì. Sửa: giai đoạn này chỉ được viết câu hỏi, không được viết câu trả lời.

**FRM-03 — hỏi làm rõ những thứ không đổi được hướng phân tích.** Hỏi "phòng tập mở cửa mấy giờ" trong khi chưa biết kinh tế một cơ sở ra sao là tiêu phí lượt hỏi. Trước mỗi câu hỏi, tự trả lời: *nếu đáp án là A thay vì B thì tôi sẽ làm khác đi ở chỗ nào?* Không trả lời được thì đừng hỏi.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.06', '001', 6, 'checklist', 'Soát trước khi nộp', '- Câu hỏi có động từ quyết định và mốc thời gian.
- Tiêu chí thành công có ít nhất một con số.
- Có tên người ra quyết định và ít nhất một ràng buộc.
- Ba dòng thêm được thông tin mà đề bài chưa nói.
- Không có câu nào là giải pháp hay kết luận.
- Đọc to lên trong 20 giây mà người nghe hiểu ngay đang giải bài gì.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.07', '001', 7, 'exercise', 'Bài nộp', 'Chọn một trong ba đề dưới đây, viết problem statement ba dòng trong **10 phút mỗi đề** (tổng 25 phút cho cả bài, gồm thời gian soát):

1. Một tiệm bánh có 3 chi nhánh muốn biết nên bán online hay mở thêm chi nhánh thứ 4.
2. Một trường ngoại ngữ thấy học viên đăng ký giảm 20% sau Tết và muốn biết nên giảm giá bao nhiêu.
3. Một công ty giao đồ ăn muốn biết nên vào thị trường Đà Nẵng trong quý tới hay không.

Với mỗi đề, ghi thêm **một câu** nói rõ bạn đã định khung lại chỗ nào so với đề gốc, và vì sao.

Output: một trang (docs hoặc markdown) gồm ba problem statement, mỗi cái đúng ba dòng, kèm một dòng "định khung lại" cho mỗi đề.');
DELETE FROM lesson_blocks WHERE lesson_id = '002';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.01', '002', 1, 'goal', 'Sau bài này bạn làm được gì', 'Viết lại một đề case thành **SCQ** — Situation, Complication, Question — để người nghe hiểu bối cảnh, hiểu vì sao bây giờ mới thành vấn đề, và biết chính xác câu hỏi đang cần trả lời, trong vòng 30 giây.

SCQ là bước ngay sau problem statement ở bài 001: problem statement là để **bạn** biết mình đang giải gì; SCQ là để **người nghe** chấp nhận rằng đó đúng là bài cần giải.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.02', '002', 2, 'concept', 'Ba phần, ba việc khác nhau', '**Situation** — những gì đúng và không ai tranh cãi. Đây là phần người nghe gật đầu. Chỉ gồm sự thật ổn định: quy mô, mô hình kinh doanh, vị trí hiện tại. Không có tính từ cảm xúc, không có nguyên nhân.

**Complication** — thứ vừa thay đổi và làm cho tình huống cũ không còn dùng được. Đây là phần khó nhất và cũng là phần phân biệt người viết giỏi: complication phải là một **sự thay đổi có thời điểm**, không phải một lời than. "Cạnh tranh gay gắt" là lời than. "Ba chuỗi mới vào thị trường trong 12 tháng qua, giá trung bình giảm 18%" là complication.

**Question** — câu hỏi quyết định, chính là dòng 1 của problem statement.

Kiểm tra nhanh một SCQ đạt: đọc xong Situation và Complication, người nghe **tự nghĩ ra** Question trước khi bạn nói. Nếu Question đến như một bất ngờ thì Complication chưa đúng.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.03', '002', 3, 'concept', 'Vì sao thứ tự này khó đảo', 'Người mới hay bắt đầu bằng câu hỏi ("Chúng ta cần quyết định có nên mở rộng không…") vì thấy nó vào thẳng vấn đề. Nhưng người nghe chưa có bối cảnh sẽ dành 30 giây tiếp theo để tự dựng lại bối cảnh trong đầu, và không nghe phần bạn đang nói.

Trật tự S → C → Q đặt người nghe vào đúng trạng thái: đồng ý → thấy có gì đó vừa gãy → cần một quyết định. Mỗi phần chuẩn bị cho phần sau. Đây cũng là bộ khung dùng lại được ở trang đầu tiên của deck và ở câu mở đầu khi thuyết trình.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.04', '002', 4, 'worked_example', 'Một đề, hai bản SCQ', '**Đề:** Một chuỗi trà sữa 15 cửa hàng, doanh thu 2 năm đi ngang 90 tỷ/năm, lợi nhuận gộp 55%. Năm ngoái chi phí mặt bằng tăng 12%, giao hàng qua app chiếm 40% đơn nhưng chiết khấu app là 25%. Chủ chuỗi hỏi có nên rút khỏi app không.

**Bản yếu:**

> *Situation:* Chuỗi trà sữa đang gặp khó khăn về lợi nhuận.
> *Complication:* Cạnh tranh ngày càng gay gắt và chi phí tăng.
> *Question:* Làm sao để tăng lợi nhuận?

Hỏng ở đâu: Situation đã cài sẵn kết luận ("gặp khó khăn"), Complication không có gì đo được, Question mơ hồ nên trả lời kiểu gì cũng được — tức là không trả lời được.

**Bản đạt:**

> *Situation:* Chuỗi có 15 cửa hàng, doanh thu ổn định 90 tỷ/năm, lợi nhuận gộp 55%. Kênh app chiếm 40% đơn hàng.
> *Complication:* Mỗi đơn qua app mất 25% chiết khấu, trong khi mặt bằng vừa tăng 12% trong 12 tháng qua. Với cơ cấu hiện tại, phần đơn tăng thêm từ app đang bào mòn lợi nhuận thay vì bù cho chi phí cố định.
> *Question:* Có nên giảm phụ thuộc vào app không, và nếu có thì giảm tới mức nào để tổng lợi nhuận năm sau không thấp hơn năm nay?

Đọc xong S và C, người nghe đã tự thấy câu hỏi trước khi tới dòng Q. Đó là dấu hiệu SCQ đạt.

Một chi tiết đáng học: bản đạt **không nói kênh app là xấu**. Nó nêu cơ cấu chi phí và để câu hỏi mở. Người viết chưa phân tích thì chưa được kết luận.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.05', '002', 5, 'pitfall', 'Ba lỗi hay gặp khi viết SCQ', '**FRM-01 — Situation chép lại đề.** Nếu Situation của bạn là ba câu đầu của đề bài viết gọn hơn, bạn chưa làm gì cả. Situation phải chọn lọc: chỉ giữ sự thật **cần thiết để hiểu Complication**, bỏ hết phần còn lại.

**FRM-02 — Complication không có số, không có mốc thời gian.** "Chi phí tăng" là trạng thái; "chi phí mặt bằng tăng 12% trong 12 tháng qua" là thay đổi. Chỉ thay đổi mới tạo ra nhu cầu quyết định.

**FRM-04 — Question thật ra là giải pháp.** "Có nên chuyển sang mô hình nhượng quyền không?" nghe như câu hỏi nhưng đã chốt sẵn hướng đi. Ở giai đoạn này, Question phải đủ rộng để nhiều phương án cùng được xét, và đủ hẹp để biết khi nào thì trả lời xong.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.06', '002', 6, 'checklist', 'Soát trước khi nộp', '- Situation chỉ chứa sự thật không ai tranh cãi, không có tính từ đánh giá.
- Complication có ít nhất một con số và một mốc thời gian.
- Người nghe đoán được Question sau khi nghe S và C.
- Question trùng với dòng 1 của problem statement, không mâu thuẫn.
- Cả ba phần đọc to trong 30 giây là hết.
- Không có câu nào kết luận thay cho phần phân tích chưa làm.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.07', '002', 7, 'exercise', 'Bài nộp', 'Viết SCQ cho **ba** đề sau, mỗi đề tối đa 8 phút:

1. Một nhà sách 12 chi nhánh, doanh thu đi ngang, muốn mở thêm 20 chi nhánh trong 24 tháng.
2. Một ứng dụng gọi xe thấy doanh thu giảm 12% một quý trong khi số chuyến không đổi.
3. Một nhà máy đồ gỗ xuất khẩu có đơn hàng tăng 30% nhưng lợi nhuận giảm.

Sau mỗi SCQ, viết một dòng: *"Complication của tôi là một thay đổi có thời điểm vì…"*. Nếu không viết nổi dòng đó, quay lại sửa Complication.

Output: một trang gồm ba SCQ, mỗi cái ba đoạn ngắn, kèm dòng tự kiểm Complication cho từng đề.');
DELETE FROM lesson_blocks WHERE lesson_id = '003';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.01', '003', 1, 'goal', 'Sau bài này bạn làm được gì', 'Viết **tiêu chí thành công đo được** cho một case, và một **bảng scope in / scope out** nói rõ cái gì bạn sẽ phân tích, cái gì cố ý không đụng tới, kèm lý do cho từng dòng loại trừ.

Đây là bài quyết định bạn có kết thúc case đúng giờ hay không. Case không bao giờ hết việc để làm; thứ duy nhất giúp bạn dừng đúng lúc là một đường biên đã vẽ sẵn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.02', '003', 2, 'concept', 'Tiêu chí thành công là điều kiện dừng, không phải lời hứa', 'Tiêu chí thành công trả lời câu: **khi nào thì tôi biết mình đã trả lời xong?** Nó luôn có ba phần:

1. **Chỉ số** — cái gì được đo. Lợi nhuận, thời gian hoàn vốn, thị phần, tỷ lệ giữ chân.
2. **Ngưỡng** — bao nhiêu thì đạt. Có con số, kể cả khi là giả định.
3. **Thời hạn** — trong bao lâu.

"Tăng lợi nhuận" thiếu cả ba. "Lợi nhuận trước thuế đạt 12 tỷ trong năm tài chính tới, tức tăng 20% so với năm nay" có đủ.

Khi khách hàng không đưa ngưỡng — trường hợp thường gặp — bạn tự đề xuất một ngưỡng và **ghi rõ đó là giả định của mình**, kèm căn cứ (mức hiện tại, mức của đối thủ, mức tối thiểu để dự án có nghĩa). Đề xuất một ngưỡng rồi kiểm chứng tốt hơn nhiều so với để trống.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.03', '003', 3, 'concept', 'Scope out mới là phần khó', 'Ai cũng viết được scope in. Giá trị nằm ở scope out, vì mỗi dòng loại trừ là một lời cam kết rằng bạn sẽ không tiêu thời gian vào đó.

Một dòng scope out đạt có hai vế: **loại trừ cái gì** và **vì sao loại được**. Lý do hợp lệ thường thuộc bốn nhóm:

- **Không đổi được kết luận** — dù đúng hay sai cũng không làm khuyến nghị khác đi.
- **Không quyết được trong phạm vi người ra quyết định** — ví dụ chính sách thuế.
- **Chi phí tìm hiểu lớn hơn giá trị** — dữ liệu phải mua, phải khảo sát nhiều tháng.
- **Đã có kết luận từ trước và không phải phần đang tranh cãi.**

Lý do không hợp lệ: "không đủ thời gian". Thời gian ít là ràng buộc chung; nó không giải thích vì sao *dòng này* bị cắt chứ không phải dòng khác.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.04', '003', 4, 'worked_example', 'Vẽ biên cho một case giao đồ ăn', '**Tình huống:** Một chuỗi cơm văn phòng 6 bếp muốn biết có nên tự xây đội giao hàng thay vì dùng app, trong 12 tháng tới. Bạn có 40 phút.

**Tiêu chí thành công:**

> Chi phí giao hàng trên mỗi đơn giảm xuống dưới 12.000đ và tỷ lệ giao đúng giờ giữ trên 92%, đạt được trong vòng 12 tháng, với vốn đầu tư ban đầu không quá 1,5 tỷ.
>
> *Giả định của tôi:* mức 12.000đ lấy từ chiết khấu app hiện tại (khoảng 22% trên đơn trung bình 55.000đ ≈ 12.100đ); 92% là mức đúng giờ hiện tại, không được phép tệ đi.

**Bảng scope:**

| Scope in | Vì sao cần |
|---|---|
| Kinh tế một đơn hàng: chi phí app hiện tại so với chi phí tự giao | Đây chính là phép so quyết định |
| Mật độ đơn theo khu vực và theo giờ | Quyết định số shipper và khả năng gộp đơn |
| Chi phí cố định của đội tự giao: lương, xe, bảo hiểm, điều phối | Phần app không thu nhưng tự làm thì phải chịu |
| Rủi ro mất đơn từ khách quen của app | Chi phí ẩn lớn nhất của việc rút khỏi app |

| Scope out | Vì sao loại được |
|---|---|
| Thiết kế app đặt hàng riêng | Không cần cho quyết định tự giao hay không; có thể dùng kênh đặt hàng hiện có |
| Mở thêm bếp mới | Là một quyết định khác, không đổi kết luận của bài này |
| Đàm phán lại chiết khấu với app | Đã đàm phán thất bại quý trước; không phải phần đang tranh cãi |
| Chính sách bảo hiểm cho tài xế công nghệ | Nằm ngoài quyền quyết định của chuỗi |

Đọc bảng này, người nghe biết chính xác 40 phút sẽ đi vào đâu — và quan trọng hơn, biết bạn **cố ý** không làm gì, thay vì tưởng bạn quên.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.05', '003', 5, 'pitfall', 'Ba lỗi làm mất tác dụng của scope', '**FRM-02 — tiêu chí không có ngưỡng.** "Giảm chi phí giao hàng" không có điểm dừng, nên bài sẽ trôi đến khi hết giờ. Sửa: đặt một con số, ghi rõ là giả định nếu chưa có dữ liệu.

**FRM-03 — hỏi làm rõ những thứ đã tự loại trừ.** Đã scope out mà vẫn tiêu lượt hỏi vào đó là tự mâu thuẫn, và người phỏng vấn sẽ nhận ra ngay. Sửa: sau khi vẽ biên, mọi câu hỏi làm rõ phải nằm trong scope in.

**FRM-04 — scope in viết như danh sách giải pháp.** "Tuyển 10 shipper" không phải phạm vi phân tích, đó là phương án. Scope in là *những câu hỏi con bạn sẽ trả lời*, không phải *những việc bạn sẽ khuyến nghị*.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.06', '003', 6, 'checklist', 'Soát trước khi nộp', '- Tiêu chí có đủ chỉ số, ngưỡng, thời hạn.
- Ngưỡng nào do bạn tự đặt thì có ghi "giả định" kèm căn cứ.
- Mỗi dòng scope out có lý do thuộc bốn nhóm hợp lệ, không có lý do "không đủ thời gian".
- Scope in là câu hỏi con, không phải giải pháp.
- Tổng số dòng scope in đủ nhỏ để làm xong trong thời lượng của case.
- Không có mục nào vừa nằm ở scope in vừa nằm ở scope out.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.07', '003', 7, 'exercise', 'Bài nộp', 'Lấy **một** đề bạn đã viết problem statement ở bài 001, dựng tiêu chí thành công và bảng scope trong 30 phút.

Yêu cầu tối thiểu: 4 dòng scope in, 4 dòng scope out, mỗi dòng scope out có lý do. Nếu một dòng loại trừ làm bạn thấy áy náy, giữ nó lại nhưng viết thêm một câu: *"nếu điều này sai thì kết luận thay đổi thế nào"* — đó là cách kiểm tra xem bạn có loại nhầm thứ quan trọng không.

Output: một bảng hai cột scope in / scope out (sheet hoặc markdown), phía trên là tiêu chí thành công ba phần, phía dưới là danh sách giả định bạn đã tự đặt.');
DELETE FROM lesson_blocks WHERE lesson_id = '004';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.01', '004', 1, 'goal', 'Sau bài này bạn làm được gì', 'Ghép ba việc của module A1 lại thành một lượt làm case thật: đọc đề → viết problem statement → **hỏi năm câu làm rõ đúng chỗ**.

Bài này là mini case đầu tiên, nên phần mới nằm ở chỗ **hỏi**. Từ đây trở đi bạn không còn được cho sẵn đầy đủ dữ kiện: đề giữ lại một phần thông tin và chỉ phát khi bạn hỏi đúng thứ.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.02', '004', 2, 'concept', 'Lượt hỏi là tài nguyên có hạn', 'Trong phỏng vấn thật bạn có khoảng 5 phút để hỏi trước khi người phỏng vấn mong bạn đi tiếp. Trong case competition, mỗi câu hỏi gửi ban giám khảo là một lần dùng quyền. Nên hỏi không phải là "thu thập càng nhiều càng tốt", mà là **chọn năm câu đổi được nhiều hướng phân tích nhất**.

Bộ lọc dùng trước mỗi câu hỏi, chỉ một câu: *nếu câu trả lời là A thay vì B, tôi sẽ làm khác đi ở chỗ nào?*

- Trả lời được → câu hỏi đáng hỏi.
- Không trả lời được → đó là sự tò mò, không phải câu hỏi phân tích.

Ba nhóm câu hỏi gần như luôn đáng hỏi trong case kinh doanh:

1. **Kinh tế một đơn vị** — một cửa hàng, một khách, một chuyến kiếm được bao nhiêu và tốn bao nhiêu. Đây là chỗ giấu phần lớn sự thật.
2. **Phân bố, không phải trung bình** — "trung bình có lãi" che mất việc 4 trong 12 điểm đang lỗ.
3. **Vì sao bây giờ** — điều gì vừa thay đổi khiến câu hỏi này xuất hiện lúc này.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.03', '004', 3, 'concept', 'Tái định nghĩa mà không cãi khách hàng', 'Khi đề bài yêu cầu "giúp triển khai cho nhanh" mà bạn thấy kế hoạch có lỗ hổng, phản xạ sai là nói "kế hoạch này sai". Phản xạ đúng là **đặt điều kiện**:

> "Em sẽ giúp triển khai. Trước đó em đề xuất kiểm hai điều kiện, vì nếu chúng chưa đạt thì mở thêm sẽ nhân rộng phần đang lỗ: (1) kinh tế một cửa hàng ở nhóm hoạt động tốt, (2) nguyên nhân lỗ của nhóm yếu. Nếu hai điều kiện đạt thì phần còn lại đúng là bài toán triển khai."

Câu này giữ nguyên mục tiêu của khách hàng, thêm một cổng kiểm tra, và nói rõ hệ quả nếu bỏ qua cổng đó. Đây là kỹ năng đáng giá nhất của module A1 và cũng là thứ rubric chấm nặng nhất.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.04', '004', 4, 'worked_example', 'Năm câu hỏi cho một đề bán lẻ', '**Đề:** Một chuỗi cà phê 9 cửa hàng, doanh thu tăng đều 8%/năm, vừa chốt kế hoạch mở thêm 15 cửa hàng trong 18 tháng và muốn bạn giúp chọn mặt bằng.

**Problem statement:**

> **Câu hỏi:** Chuỗi có nên mở 15 cửa hàng trong 18 tháng không, và điều kiện nào phải đạt trước khi ký mặt bằng đầu tiên?
> **Tiêu chí:** mỗi cửa hàng mới hoà vốn trong 12 tháng và không kéo doanh thu cửa hàng cũ trong bán kính 1 km giảm quá 5%.
> **Người quyết định:** ban giám đốc, vốn tự có 25 tỷ, không tăng vay.

**Năm câu hỏi, và vì sao mỗi câu đáng hỏi:**

| Câu hỏi | Nếu trả lời khác đi thì sao |
|---|---|
| Một cửa hàng đang lãi bao nhiêu sau khi trừ toàn bộ chi phí phân bổ? | Lãi mỏng thì nhân rộng làm hỏng nhanh hơn; lãi dày thì bài chuyển sang chọn mặt bằng thật |
| Chín cửa hàng đó phân bố lãi lỗ thế nào, có cửa hàng nào lỗ không? | Có cửa hàng lỗ thì phải tìm nguyên nhân trước khi mở thêm |
| Cửa hàng mới nhất mất bao lâu để hoà vốn? | Đây là dự báo tốt nhất cho 15 cửa hàng sắp mở |
| Doanh thu tăng 8% đến từ giá, lượng khách, hay tần suất? | Tăng nhờ giá thì mở rộng không nhân được đà tăng đó |
| Vì sao là bây giờ và vì sao là 15? | Con số 15 thường đến từ một mục tiêu đã hứa, không từ phân tích |

**Câu không nên hỏi, dù rất muốn:** menu có bao nhiêu món, dùng máy pha nào, quán mở mấy giờ. Đúng là thông tin, nhưng dù trả lời thế nào thì hướng phân tích vẫn thế — đó là **FRM-03**.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.05', '004', 5, 'pitfall', 'Bốn kiểu hỏng trong mini case đầu tiên', '**FRM-04 — nhận luôn đề bài và bắt tay chọn mặt bằng.** Đây là bẫy chính của dạng đề "giúp tôi triển khai". Dấu hiệu: câu đầu tiên của bạn đã là một giải pháp. Rubric của bài này chặn trần ở mức 2 nếu bạn chỉ nhắc lại kế hoạch mở rộng.

**FRM-01 — problem statement chép lại đề.** "Chuỗi muốn mở thêm 15 cửa hàng" không thêm thông tin nào.

**FRM-03 — tiêu lượt hỏi vào chi tiết không đổi hướng.** Năm câu là năm cơ hội; đừng đổi một cơ hội lấy một chi tiết trang trí.

**FRM-02 — tiêu chí thành công không có số.** "Mở rộng hiệu quả" không nói được khi nào thì dừng.

Một lỗi tinh vi hơn, không có mã riêng: **hỏi năm câu cùng nhóm**. Năm câu đều về chi phí mặt bằng thì bạn chỉ soi được một cạnh. Rải câu hỏi qua ít nhất ba nhóm khác nhau.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.06', '004', 6, 'checklist', 'Soát trước khi nộp', '- Problem statement đủ ba dòng và có tái định nghĩa so với đề gốc.
- Đúng năm câu hỏi, không nhiều hơn.
- Mỗi câu hỏi kèm một dòng "nếu trả lời khác thì tôi làm khác ở đâu".
- Có ít nhất một câu về kinh tế một đơn vị.
- Có ít nhất một câu về phân bố lãi lỗ, không phải trung bình.
- Không câu nào hỏi thứ mình đã tự loại khỏi phạm vi.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('004.07', '004', 7, 'exercise', 'Bài nộp', 'Làm đề **C-004 — Chuỗi nhà sách muốn mở thêm 20 cửa hàng** trong 25 phút, tính cả thời gian đọc đề.

Cách làm: đọc đề, viết problem statement ba dòng, rồi viết năm câu hỏi làm rõ kèm lý do cho từng câu. Dữ liệu của đề chỉ được phát khi bạn hỏi đúng — nên hãy hỏi trước, rồi mới xem phần được phát.

Output: một trang gồm problem statement ba dòng, bảng năm câu hỏi (cột câu hỏi · cột "nếu trả lời khác thì làm khác ở đâu"), và một câu nói rõ bạn đã tái định nghĩa vấn đề ở chỗ nào.');
DELETE FROM lesson_blocks WHERE lesson_id = '009';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.01', '009', 1, 'goal', 'Sau bài này bạn làm được gì', 'Vẽ được **sơ đồ dòng tiền vào – ra** của một doanh nghiệp bất kỳ trong 15 phút: tiền vào từ ai, đi qua những chặng chi phí nào, còn lại bao nhiêu, và **chặng nào ăn mất nhiều nhất**.

Đây là kỹ năng nền của mọi case profitability. Không có nó, bạn chỉ có thể nói "chi phí cao quá" — có nó, bạn nói được "70% chi phí nằm ở giá vốn, và một điểm phần trăm ở đó bằng cả ngân sách marketing một quý".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.02', '009', 2, 'concept', 'Bốn chặng của một đồng doanh thu', 'Mỗi đồng khách trả đi qua bốn chặng, theo đúng thứ tự này. Học thuộc thứ tự quan trọng hơn học thuộc tên gọi kế toán:

1. **Giá vốn (COGS)** — tiền phải bỏ ra để tạo ra chính món đã bán. Nguyên liệu, hàng nhập, lương người trực tiếp làm. Còn lại: **lợi nhuận gộp**.
2. **Chi phí bán hàng và tiếp thị** — tiền để có được khách đó. Quảng cáo, khuyến mãi, hoa hồng, chiết khấu sàn.
3. **Chi phí vận hành cố định** — tiền trả dù bán được hay không. Mặt bằng, lương quản lý, phần mềm, khấu hao. Sau chặng này còn lại: **lợi nhuận hoạt động**.
4. **Lãi vay và thuế** — phần chia cho ngân hàng và nhà nước. Còn lại: **lợi nhuận sau thuế**.

Ba câu hỏi phải trả lời được sau khi vẽ xong:

- **Biên gộp bao nhiêu?** Dưới 20% là mô hình mỏng, mọi biến động nhỏ đều đau. Trên 60% là mô hình có chỗ để chịu đựng.
- **Chi phí nào là biến đổi, chi phí nào cố định?** Đây là chỗ quyết định doanh nghiệp sống hay chết khi doanh thu tụt 30%.
- **Hoà vốn ở mức nào?** Cần bán bao nhiêu để phủ hết phần cố định.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.03', '009', 3, 'concept', 'Biến đổi hay cố định quan trọng hơn to hay nhỏ', 'Người mới nhìn bảng chi phí và chỉ tay vào dòng lớn nhất. Người có kinh nghiệm hỏi trước: dòng đó **có co lại khi doanh thu co lại không?**

| | Chi phí biến đổi | Chi phí cố định |
|---|---|---|
| Ví dụ | Nguyên liệu, chiết khấu sàn, phí giao hàng | Mặt bằng, lương quản lý, khấu hao |
| Khi doanh thu tăng | Tăng theo, biên gộp gần như giữ nguyên | Không đổi → lợi nhuận bật lên nhanh |
| Khi doanh thu giảm 30% | Giảm theo, đau vừa phải | Không giảm → lỗ ngay |
| Đòn bẩy để cải thiện | Giá mua, định lượng, tỷ lệ hao hụt | Công suất sử dụng, đàm phán lại hợp đồng |

Hệ quả thực tế: một doanh nghiệp **nặng chi phí cố định** (phòng gym, rạp chiếu phim, nhà máy) thì câu hỏi trung tâm luôn là *lấp đầy công suất*. Một doanh nghiệp **nặng chi phí biến đổi** (bán lẻ, thương mại điện tử) thì câu hỏi trung tâm là *biên trên mỗi đơn*. Nhận ra doanh nghiệp thuộc loại nào trong 2 phút đầu là bạn đã đi đúng đường.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.04', '009', 4, 'worked_example', 'Sơ đồ dòng tiền của một tiệm bánh mì', '**Dữ kiện:** Tiệm bán 300 ổ/ngày, giá 25.000đ/ổ, mở 30 ngày/tháng. Nguyên liệu 9.000đ/ổ. Hai nhân viên làm bánh lương 8 triệu/người/tháng. Mặt bằng 30 triệu/tháng. Điện nước, bao bì, hao hụt khoảng 1.500đ/ổ. Chủ tiệm tự quản lý, không lấy lương. Chạy quảng cáo 5 triệu/tháng.

**Bước 1 — doanh thu tháng:** 300 × 25.000 × 30 = **225 triệu**.

**Bước 2 — giá vốn:** nguyên liệu 9.000 + biến đổi khác 1.500 = 10.500đ/ổ → 300 × 10.500 × 30 = 94,5 triệu. Lương hai thợ làm bánh là chi phí trực tiếp: 16 triệu. Tổng giá vốn **110,5 triệu**.

**Bước 3 — lợi nhuận gộp:** 225 − 110,5 = **114,5 triệu**, biên gộp **50,9%**.

**Bước 4 — marketing và cố định:** quảng cáo 5 triệu + mặt bằng 30 triệu = 35 triệu.

**Bước 5 — lợi nhuận hoạt động:** 114,5 − 35 = **79,5 triệu/tháng**, biên hoạt động **35,3%**.

**Bước 6 — đọc sơ đồ:**

| Chặng | Số tiền (triệu/tháng) | % doanh thu | Loại |
|---|---|---|---|
| Doanh thu | 225 | 100% | — |
| Nguyên liệu + biến đổi khác | 94,5 | 42,0% | biến đổi |
| Lương thợ | 16 | 7,1% | gần cố định |
| Mặt bằng | 30 | 13,3% | cố định |
| Quảng cáo | 5 | 2,2% | tuỳ ý |
| **Còn lại** | **79,5** | **35,3%** | — |

**Bước 7 — hoà vốn:** phần cố định là 16 + 30 + 5 = 51 triệu/tháng. Lãi gộp mỗi ổ = 25.000 − 10.500 = 14.500đ. Cần 51.000.000 ÷ 14.500 ≈ **3.517 ổ/tháng**, tức khoảng **117 ổ/ngày** — bằng 39% mức hiện tại. Tiệm có đệm an toàn dày.

**Bước 8 — ba đòn bẩy, xếp theo sức nặng:**

1. **Giá nguyên liệu (42% doanh thu).** Giảm 5% giá nhập nguyên liệu (81 triệu/tháng) = tiết kiệm 4,1 triệu/tháng, gần bằng một tháng quảng cáo.
2. **Sản lượng trên cùng mặt bằng (mặt bằng 13,3% và cố định).** Bán thêm 50 ổ/ngày không tốn thêm tiền thuê: +21,8 triệu lãi gộp/tháng.
3. **Giá bán.** Tăng 1.000đ/ổ = +9 triệu/tháng nếu lượng không đổi — nhưng đây là đòn bẩy rủi ro nhất vì phải kiểm phản ứng của khách.

Chú ý cách xếp hạng: **theo phần trăm doanh thu nhân với khả năng thay đổi được**, không theo cảm giác. Quảng cáo là dòng dễ cắt nhất nhưng chỉ chiếm 2,2% — cắt sạch cũng không cứu được gì.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.05', '009', 5, 'pitfall', 'Bốn lỗi khi đọc dòng tiền', '**BIZ-01 — nhầm doanh thu với lợi nhuận.** "Tiệm này doanh thu 225 triệu, sống tốt" là câu nói không có thông tin. Với biên gộp 20% thì cùng doanh thu ấy có thể đang lỗ. Sửa: mọi câu về sức khoẻ tài chính phải đi kèm một biên.

**FIN-05 — tính biên gộp rồi gọi là lợi nhuận.** Biên gộp 50,9% nghe rất khoẻ, nhưng sau mặt bằng và quảng cáo chỉ còn 35,3%, và nếu chủ tiệm lấy lương thì còn ít hơn. Luôn nói rõ đang ở chặng nào.

**BIZ-03 — bỏ qua chi phí phục vụ khách hàng.** Bao bì, hao hụt, phí giao hàng, chiết khấu sàn hay bị để ngoài vì "nhỏ". Trong ví dụ trên, 1.500đ/ổ tưởng nhỏ nhưng bằng 13,5 triệu/tháng — gấp gần ba lần ngân sách quảng cáo.

**FIN-02 — bỏ qua dòng tiền.** Lợi nhuận và tiền mặt là hai thứ khác nhau: hàng tồn, công nợ và tiền thuê trả trước có thể làm một doanh nghiệp có lãi vẫn hết tiền. Bài này chỉ vẽ lợi nhuận; nhớ rằng đó chưa phải toàn bộ câu chuyện.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.06', '009', 6, 'checklist', 'Soát trước khi nộp', '- Sơ đồ có đủ bốn chặng, không nhảy cóc từ doanh thu xuống lợi nhuận.
- Mỗi dòng chi phí ghi kèm **% doanh thu**, không chỉ số tuyệt đối.
- Mỗi dòng được gắn nhãn biến đổi / cố định / tuỳ ý.
- Có tính điểm hoà vốn và so với mức hoạt động hiện tại.
- Ba đòn bẩy xếp hạng theo độ lớn × khả năng thay đổi, có số đi kèm.
- Giả định nào do bạn tự đặt đều được ghi rõ là giả định.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('009.07', '009', 7, 'exercise', 'Bài nộp', 'Chọn **một** doanh nghiệp bạn quan sát được trực tiếp (quán ăn quen, tiệm giặt, phòng gym, shop online của bạn bè) và vẽ sơ đồ dòng tiền vào – ra trong 30 phút.

Không có số thật thì tự đặt giả định và ghi rõ nguồn suy ra (quan sát, hỏi chủ quán, hay ước lượng). Mục tiêu là **chuỗi lập luận đúng**, không phải số chính xác.

Output: một sheet gồm bảng bốn chặng (số tiền · % doanh thu · nhãn biến đổi/cố định), ô tính điểm hoà vốn, và ba dòng đòn bẩy xếp hạng kèm ước lượng tác động bằng tiền.');
DELETE FROM lesson_blocks WHERE lesson_id = '010';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.01', '010', 1, 'goal', 'Sau bài này bạn làm được gì', 'Nhận ra **mô hình doanh thu** của một doanh nghiệp trong vòng một câu hỏi, và nói được ba điều đi kèm từng mô hình: tiền vào lúc nào, chỉ số sống còn là gì, và mô hình đó chết vì cái gì.

Giá trị thực tế: khi biết một công ty chạy mô hình đăng ký thuê bao, bạn biết ngay phải hỏi về tỷ lệ rời bỏ và chi phí thu hút khách — không cần ai nhắc. Đó là cách người có kinh nghiệm đặt câu hỏi nhanh hơn người mới.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.02', '010', 2, 'concept', 'Bảy mô hình và chỉ số sống còn của từng cái', '| Mô hình | Tiền vào khi nào | Chỉ số sống còn | Chết vì |
|---|---|---|---|
| **Bán đứt** (bán lẻ, nhà hàng, sản xuất) | Ngay khi bán | Biên gộp × vòng quay hàng | Tồn kho ế và biên mỏng |
| **Thuê bao** (phần mềm, phòng gym, học phí tháng) | Đều đặn hàng kỳ | Tỷ lệ rời bỏ và LTV/CAC | Khách rời nhanh hơn tốc độ có khách mới |
| **Sàn trung gian** (giao đồ ăn, gọi xe, chợ điện tử) | Hoa hồng mỗi giao dịch | Mật độ hai phía và tỷ lệ lấp đơn | Trợ giá mãi không đạt mật độ tự sống |
| **Quảng cáo** (báo, mạng xã hội, ứng dụng miễn phí) | Khi có lượt xem | Thời lượng dùng × giá mỗi nghìn lượt | Lưu lượng phụ thuộc một nguồn duy nhất |
| **Nhượng quyền** (chuỗi F&B, giáo dục) | Phí ban đầu + % doanh thu | Số điểm mở mới × tỷ lệ điểm sống sót | Chất lượng điểm nhượng quyền kéo sập thương hiệu |
| **Dùng bao nhiêu trả bấy nhiêu** (điện nước, đám mây, logistics) | Theo mức dùng | Công suất sử dụng và biên biến đổi | Chi phí cố định lớn mà công suất thấp |
| **Dao cạo – lưỡi dao** (máy in và mực, máy pha và viên nén) | Ít lúc đầu, nhiều về sau | Tỷ lệ mua lại phần tiêu hao | Hàng tiêu hao bị bên thứ ba thay thế |

Học bảng này không phải để thuộc lòng, mà để **chuyển từ tên mô hình sang câu hỏi cần hỏi**. Nghe "chuỗi phòng gym bán gói năm" là lập tức hỏi: bao nhiêu phần trăm hội viên còn đến sau 3 tháng? Vì ở mô hình thuê bao, người đã trả tiền mà bỏ tập là doanh thu năm nay đẹp và năm sau sụp.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.03', '010', 3, 'concept', 'Cùng một sản phẩm, đổi mô hình là đổi cả bài toán', 'Một phòng tập có thể chạy ba mô hình khác nhau trên cùng một cơ sở vật chất:

- **Bán gói năm trả trước** — tiền vào ngay, dòng tiền khoẻ, nhưng doanh thu ghi nhận trước khi phục vụ xong; rủi ro là bán được nhiều mà năm sau không ai gia hạn.
- **Thu tháng** — dòng tiền mỏng hơn, nhưng mỗi tháng là một lần khách bỏ phiếu bằng tiền, nên chất lượng dịch vụ được kiểm liên tục.
- **Trả theo buổi** — rủi ro thấp cho khách, doanh thu lên xuống theo mùa, và câu hỏi trung tâm chuyển thành lấp đầy khung giờ thấp điểm.

Cùng một phòng tập, ba mô hình, ba câu hỏi phân tích hoàn toàn khác. Khi đề case nói "doanh thu giảm", câu đầu tiên bạn nên hỏi là **doanh thu theo mô hình nào** — vì cách sửa khác hẳn nhau.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.04', '010', 4, 'worked_example', 'Đọc mô hình từ ba mẩu thông tin', '**Tình huống:** Một ứng dụng học tiếng Anh cho biết: tải về miễn phí, 4% người dùng mua gói 299.000đ/năm, phần còn lại xem quảng cáo. Chi phí quảng cáo để có một người tải là 12.000đ. Mỗi người dùng miễn phí mang về khoảng 8.000đ/năm từ quảng cáo. Gói trả phí gia hạn năm thứ hai là 55%.

**Bước 1 — nhận mô hình:** đây là **hai mô hình chồng lên nhau**: thuê bao (4% trả phí) cộng quảng cáo (96% còn lại). Đừng phân tích như một mô hình duy nhất.

**Bước 2 — doanh thu trung bình trên mỗi người tải, năm 1:**

- Từ trả phí: 4% × 299.000 = 11.960đ
- Từ quảng cáo: 96% × 8.000 = 7.680đ
- **Tổng: 19.640đ**, so với chi phí thu hút 12.000đ → còn **7.640đ** ngay trong năm đầu.

**Bước 3 — nhìn sang năm 2:** nhóm trả phí gia hạn 55% → 4% × 55% = 2,2% người dùng ban đầu tiếp tục trả, mang về 2,2% × 299.000 = 6.578đ, cộng quảng cáo (giả định giữ nguyên 7.680đ) = **14.258đ**, và lần này **không tốn chi phí thu hút**.

**Bước 4 — kết luận đọc ra được:** mô hình lành, nhưng **chỉ số quyết định là 4%**, không phải giá gói. Tăng tỷ lệ chuyển đổi từ 4% lên 5% thêm 2.990đ/người tải — nhiều hơn cả việc tăng giá gói 10% (thêm 1.196đ) và ít rủi ro hơn.

**Bước 5 — câu hỏi tiếp theo phải hỏi**, đúng theo mô hình:

1. 4% chuyển đổi xảy ra ở thời điểm nào sau khi tải — ngày đầu hay sau 2 tuần dùng?
2. Người gia hạn khác người không gia hạn ở hành vi nào (số buổi học/tuần)?
3. Doanh thu quảng cáo 8.000đ/năm đến từ bao nhiêu phiên dùng — nếu người dùng bỏ app sau 1 tháng thì con số đó có còn đúng không?

Chú ý bước 5: câu hỏi không đến từ trí nhớ mà **đến từ mô hình**. Thuê bao → hỏi chuyển đổi và giữ chân. Quảng cáo → hỏi thời lượng dùng.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.05', '010', 5, 'pitfall', 'Lỗi hay gặp khi phân loại mô hình', '**BIZ-02 — liệt kê canvas mà không rút ra đòn bẩy.** Gọi tên được mô hình là bước một; nếu dừng ở đó thì bạn mới mô tả, chưa phân tích. Mỗi lần gọi tên mô hình, bắt buộc kèm một câu: *"nên chỉ số quyết định ở đây là …"*.

**BIZ-04 — giả định biên lợi nhuận không có cơ sở.** "Phần mềm thì biên 80%" là khuôn mẫu, không phải dữ liệu; một app học tiếng Anh có chi phí nội dung và chi phí máy chủ rất khác nhau tuỳ cách vận hành. Nếu phải giả định, nói rõ đang giả định và neo vào một con số quan sát được.

**FIN-06 — bỏ chi phí thu hút khách ra khỏi mô hình.** Doanh thu 19.640đ/người nghe hay cho tới khi trừ 12.000đ chi phí quảng cáo. Ở mọi mô hình có mua lưu lượng, CAC phải nằm trong phép tính ngay từ đầu chứ không phải một dòng ghi chú cuối trang.

**FIN-07 — chọn đơn vị không khớp cách công ty vận hành.** Với ứng dụng trên, đơn vị đúng là *một người tải*, không phải *một người trả phí* — vì tiền quảng cáo thu từ cả nhóm miễn phí. Chọn sai đơn vị thì mọi phép tính sau đó lệch.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.06', '010', 6, 'checklist', 'Soát trước khi nộp', '- Mỗi doanh nghiệp được gán đúng mô hình, và nếu chồng nhiều mô hình thì tách rõ từng phần.
- Mỗi mô hình kèm chỉ số sống còn tương ứng, không phải chỉ số chung chung.
- Có ít nhất một ví dụ Việt Nam cho mỗi mô hình, ghi rõ là quan sát hay giả định.
- Đơn vị phân tích khớp với cách doanh nghiệp thật sự kiếm tiền.
- Chi phí thu hút khách nằm trong phép tính, không nằm ở chú thích.
- Mỗi mô hình có một dòng "chết vì cái gì".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('010.07', '010', 7, 'exercise', 'Bài nộp', 'Lập bảng so sánh **bảy mô hình** với các cột: mô hình · ví dụ Việt Nam bạn quan sát được · tiền vào lúc nào · chỉ số sống còn · chết vì cái gì · một câu hỏi bạn sẽ hỏi đầu tiên nếu gặp case thuộc mô hình này.

Sau bảng, chọn **một** doanh nghiệp chạy **hai mô hình chồng nhau** (ví dụ: quán cà phê vừa bán tại chỗ vừa bán gói thành viên) và viết nửa trang: hai mô hình đó hỗ trợ nhau hay giành nguồn lực của nhau, và đâu là dấu hiệu để biết.

Thời lượng 30 phút. Ví dụ Việt Nam không cần số chính xác, nhưng phải ghi rõ chỗ nào là quan sát và chỗ nào là bạn đoán.

Output: một bảng bảy dòng × sáu cột, kèm nửa trang phân tích trường hợp hai mô hình chồng nhau.');
DELETE FROM lesson_blocks WHERE lesson_id = '011';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.01', '011', 1, 'goal', 'Sau bài này bạn làm được gì', 'Mổ xẻ (*teardown*) một doanh nghiệp bạn chưa từng nghiên cứu, trong 35 phút, và nộp: **canvas một trang** + **ba đòn bẩy lợi nhuận** xếp hạng + **một rủi ro mô hình**.

Teardown là bài tổng hợp của module A3: bài 009 cho bạn dòng tiền, bài 010 cho bạn mô hình doanh thu, bài này bắt bạn dùng cả hai trên một tình huống có **hai mô hình để so sánh** — điểm mạnh của việc so sánh là nó phơi bày ngay cái gì là bản chất, cái gì chỉ là chi tiết.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.02', '011', 2, 'concept', 'Canvas một trang, sáu ô, không hơn', 'Canvas đầy đủ có chín ô; trong case bạn chỉ cần sáu ô trả lời được câu "doanh nghiệp này kiếm tiền thế nào":

1. **Khách trả tiền là ai** — và có khác người sử dụng không (báo miễn phí: người đọc dùng, nhà quảng cáo trả).
2. **Bán cái gì, tính tiền theo đơn vị nào** — mỗi món, mỗi tháng, mỗi giao dịch, mỗi giờ.
3. **Chi phí tạo ra một đơn vị đó** — phần biến đổi.
4. **Chi phí phải trả dù không bán được gì** — phần cố định.
5. **Tiền vào trước hay sau khi phục vụ** — quyết định rủi ro dòng tiền.
6. **Cái gì chặn người khác làm giống hệt** — thương hiệu, hợp đồng, vị trí, quy mô, hay không có gì.

Ô số 6 là ô hay bị bỏ nhất và cũng là ô nói nhiều nhất về tương lai. Nếu câu trả lời là "không có gì", thì mọi khoản lợi nhuận đang thấy đều tạm thời.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.03', '011', 3, 'concept', 'Đòn bẩy phải xếp hạng, không được liệt kê ngang hàng', 'Ba đòn bẩy là kết quả cuối cùng của teardown, và phải xếp theo **tác động × khả năng làm được**:

- **Tác động**: thay đổi một điểm phần trăm ở dòng này thì lợi nhuận đổi bao nhiêu tiền. Dòng chiếm 40% doanh thu luôn mạnh hơn dòng chiếm 3%, dù dòng 3% dễ cắt hơn.
- **Khả năng làm được**: có nằm trong tay người ra quyết định không, mất bao lâu, có phá thứ khác không (giảm định lượng để tiết kiệm nguyên liệu thì mất khách).

Liệt kê tám đề xuất ngang hàng là **REC-03** — dấu hiệu của người chưa dám chọn. Ba đòn bẩy xếp hạng, có số đi kèm, luôn giá trị hơn tám gạch đầu dòng.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.04', '011', 4, 'worked_example', 'Hai quán cà phê, một phép so sánh', '**Tình huống:** Quán A do chủ tự vận hành. Quán B nhượng quyền từ một chuỗi. Cùng mặt bằng 40 m², cùng khu, cùng bán khoảng 200 ly/ngày.

| | Quán A — tự vận hành | Quán B — nhượng quyền |
|---|---|---|
| Giá trung bình mỗi ly | 35.000đ | 45.000đ |
| Nguyên liệu mỗi ly | 11.000đ | 13.000đ (mua qua chuỗi) |
| Phí nhượng quyền | — | 6% doanh thu |
| Đầu tư ban đầu | 350 triệu | 900 triệu (gồm phí ban đầu 200 triệu) |
| Mặt bằng + nhân sự + vận hành / tháng | 75 triệu | 95 triệu (theo chuẩn chuỗi) |
| Marketing | tự làm, ~3 triệu/tháng | chuỗi làm, đã gồm trong phí |

**Bước 1 — doanh thu tháng:** A: 200 × 35.000 × 30 = **210 triệu**. B: 200 × 45.000 × 30 = **270 triệu**.

**Bước 2 — lãi gộp:** A: (35.000 − 11.000) × 200 × 30 = **144 triệu** (biên 68,6%). B: (45.000 − 13.000) × 200 × 30 = **192 triệu** (biên 71,1%).

**Bước 3 — trừ phí nhượng quyền của B:** 6% × 270 = 16,2 triệu → còn **175,8 triệu**.

**Bước 4 — trừ chi phí cố định:** A: 144 − 75 − 3 = **66 triệu/tháng**. B: 175,8 − 95 = **80,8 triệu/tháng**.

**Bước 5 — hoàn vốn:** A: 350 ÷ 66 ≈ **5,3 tháng**. B: 900 ÷ 80,8 ≈ **11,1 tháng**.

**Bước 6 — đọc kết quả, và đây mới là phần có giá trị:**

Quán B kiếm nhiều tiền hơn mỗi tháng (+22%), nhưng **rủi ro cho người bỏ vốn cao hơn hẳn**, vì ba lý do đọc thẳng ra từ bảng:

1. **Vốn ban đầu gấp 2,6 lần** và phần lớn không lấy lại được nếu đóng cửa (phí nhượng quyền 200 triệu là chi phí chìm ngay khi ký).
2. **Chi phí cố định cao hơn 20 triệu/tháng** theo chuẩn chuỗi, nên khi doanh thu giảm 30%, B lỗ trước A: lãi gộp B còn 123 triệu − 95 = 28 triệu, còn A còn 100,8 − 78 = 22,8 triệu… *trên giấy A thấp hơn, nhưng A cắt được nhân sự và marketing, B thì bị ràng buộc bởi chuẩn chuỗi.* Khả năng co giãn mới là thứ quyết định.
3. **Phí 6% tính trên doanh thu, không phải lợi nhuận.** Tháng ế vẫn phải trả — đây là điểm khác biệt bản chất giữa hai mô hình.

Đổi lại, B mua được ba thứ A không có: nhận diện thương hiệu (nên bán được giá cao hơn 10.000đ/ly), quy trình sẵn, và marketing tập trung. Câu trả lời đúng cho đề này không phải "chọn A" hay "chọn B" mà là **B đắt hơn để đổi lấy tốc độ và giảm rủi ro vận hành, A rẻ hơn nhưng dồn rủi ro vào năng lực của chính người chủ**.

**Ba đòn bẩy cho quán A**, xếp hạng:

1. **Giá bán (chênh 10.000đ/ly so với B).** Nếu A cải thiện chất lượng và không gian để tăng giá 5.000đ/ly: +30 triệu lãi gộp/tháng — lớn hơn mọi khoản tiết kiệm chi phí khả dĩ.
2. **Nguyên liệu 31,4% doanh thu.** Giảm 8% giá nhập: +5,3 triệu/tháng.
3. **Số ly bán ra trên cùng mặt bằng.** Thêm 30 ly/ngày: +21,6 triệu lãi gộp/tháng, không tăng tiền thuê.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.05', '011', 5, 'pitfall', 'Bốn lỗi trong một bài teardown', '**BIZ-02 — liệt kê canvas mà không rút ra đòn bẩy.** Sáu ô điền đầy đủ nhưng kết bài bằng "mô hình khá hoàn chỉnh" là bài chưa xong. Canvas là phương tiện; đòn bẩy mới là sản phẩm.

**BIZ-01 — nhầm doanh thu với lợi nhuận.** "B tốt hơn vì doanh thu 270 so với 210" bỏ qua phí nhượng quyền và chi phí cố định cao hơn.

**FIN-08 — đưa chi phí chìm vào quyết định.** Nếu đề hỏi "có nên đóng quán không", thì 200 triệu phí nhượng quyền **đã trả rồi** không được tính vào phép so sánh tương lai. Chi phí chìm chỉ có ý nghĩa khi quyết định *trước* lúc chi.

**REC-03 — liệt kê tám đề xuất ngang hàng.** Chọn ba, xếp hạng, có số. Nếu thấy khó chọn thì đó chính là công việc đang cần làm, không phải lý do để liệt kê tất cả.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.06', '011', 6, 'checklist', 'Soát trước khi nộp', '- Canvas đủ sáu ô, ô "cái gì chặn người khác làm giống hệt" không bỏ trống.
- Có so sánh bằng số giữa hai mô hình, không chỉ mô tả định tính.
- Có tính hoàn vốn hoặc một thước đo rủi ro vốn tương đương.
- Ba đòn bẩy xếp hạng, mỗi cái kèm ước lượng tác động bằng tiền.
- Có nêu ít nhất một rủi ro thuộc về **mô hình**, không phải rủi ro chung chung kiểu "cạnh tranh gay gắt".
- Không dùng chi phí đã chi để biện minh cho quyết định sắp tới.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('011.07', '011', 7, 'exercise', 'Bài nộp', 'Làm đề **C-011 — Quán cà phê tự vận hành và quán nhượng quyền** trong 35 phút.

Yêu cầu: canvas sáu ô cho **cả hai** mô hình, một bảng so sánh bằng số (doanh thu, lãi gộp, chi phí cố định, lợi nhuận tháng, thời gian hoàn vốn), ba đòn bẩy xếp hạng cho mô hình bạn cho là phù hợp hơn với người bỏ vốn lần đầu, và một rủi ro mô hình kèm dấu hiệu nhận biết sớm.

Số liệu trong đề chỉ được phát khi bạn hỏi đúng thứ — hãy hỏi theo mô hình như bài 010 chỉ ra, đừng hỏi lan man.

Output: canvas một trang (hai cột cho hai mô hình), bảng so sánh số liệu, ba dòng đòn bẩy có ước lượng bằng tiền, và một đoạn ngắn về rủi ro mô hình.');
DELETE FROM lesson_blocks WHERE lesson_id = '019';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.01', '019', 1, 'goal', 'Sau bài này bạn làm được gì', 'Ước lượng quy mô một thị trường **từ dưới lên** — đi từ một đơn vị cung có thật (một cửa hàng, một xe, một nhân viên bán hàng) rồi nhân lên — và nói được vì sao con số của bạn lệch so với cách top-down.

Cụ thể, bạn sẽ nộp một bảng tính có: chuỗi nhân tử, ô giả định tách riêng, kết quả bottom-up, kết quả top-down, và một dòng giải thích chênh lệch.

Không thuộc bài này: chọn chiến lược thâm nhập, định giá, hay dự báo tăng trưởng nhiều năm. Ở đây chỉ có một câu hỏi: **thị trường này to cỡ nào, và tôi tin con số đó tới đâu**.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.02', '019', 2, 'concept', 'Bottom-up là đếm đơn vị cung, top-down là chia đơn vị cầu', 'Top-down bắt đầu từ một tổng lớn rồi cắt dần: dân số → nhóm tuổi → tỷ lệ dùng → chi tiêu mỗi người. Bottom-up bắt đầu từ một đơn vị bạn quan sát được rồi nhân lên: một cửa hàng bán bao nhiêu một ngày → bao nhiêu cửa hàng → bao nhiêu ngày mở cửa.

Chọn bottom-up khi:

- Bạn quan sát được đơn vị cung, hoặc đếm được nó trên bản đồ, trong báo cáo, ngoài đường.
- Đề hỏi về một phân khúc hẹp mà số tổng ngành không nói được gì (một quận, một kênh bán, một nhóm khách B2B).
- Bạn cần một con số **kiểm chứng chéo** cho kết quả top-down vừa tính.

Chọn top-down khi đơn vị cung quá phân mảnh để đếm, hoặc khi bạn chỉ có dữ liệu vĩ mô.

Câu quan trọng nhất của bài này: **hai cách không thay thế nhau, chúng kiểm tra nhau.** Một người làm case giỏi tính cả hai khi có thời gian, rồi dùng khoảng cách giữa hai kết quả để biết giả định nào của mình yếu nhất.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.03', '019', 3, 'concept', 'Chuỗi bottom-up luôn có ba tầng', 'Mọi chuỗi bottom-up dùng được đều có đúng ba loại nhân tử. Thiếu tầng nào là chuỗi sai ở đó:

1. **Số đơn vị** — bao nhiêu cửa hàng, xe, máy, nhân viên. Đây là tầng dễ đếm nhất và cũng dễ kiểm tra nhất.
2. **Sản lượng mỗi đơn vị mỗi lần** — một cửa hàng phục vụ bao nhiêu khách một giờ, một xe chở bao nhiêu chuyến.
3. **Tần suất** — bao nhiêu giờ hoạt động một ngày, bao nhiêu ngày một năm, khách quay lại mấy lần.

Viết chuỗi ra thành một hàng nhân tử trước khi điền số. Nếu không viết ra được hàng đó, bạn chưa hiểu thị trường chứ không phải thiếu dữ liệu.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.04', '019', 4, 'worked_example', 'Đếm ngược từ một quán cà phê', 'Đề: ước lượng doanh thu cà phê mang đi trong một quận nội thành, một năm.

Bước 1 — chọn đơn vị cung: một quán cà phê mang đi. Đếm được bằng cách đi một vòng vài con phố rồi suy ra mật độ.

Bước 2 — viết chuỗi trước khi điền số:

```
Doanh thu = số quán × ly/giờ × giờ mở/ngày × ngày/năm × giá/ly
```

Bước 3 — điền giả định, mỗi ô ghi rõ mình lấy ở đâu (A = quan sát, B = suy ra, C = đoán):

| Nhân tử | Giá trị | Loại | Ghi chú |
|---|---|---|---|
| Số quán trong quận | 250 | B | đếm 12 quán trên 3 phố, nhân theo số phố tương đương |
| Ly mỗi giờ (trung bình cả ngày) | 8 | C | giờ cao điểm ~20, thấp điểm ~3 |
| Giờ mở mỗi ngày | 12 | A | quan sát biển giờ mở cửa |
| Ngày mở mỗi năm | 350 | B | nghỉ Tết vài ngày |
| Giá mỗi ly | 30.000đ | A | bảng giá |

Bước 4 — nhân: 250 × 8 × 12 × 350 × 30.000 ≈ **252 tỷ đồng/năm**.

Bước 5 — kiểm tra chéo bằng top-down: quận có ~300 nghìn dân, giả sử 25% uống cà phê mua ngoài, trung bình 2 ly/tuần, 30.000đ/ly → 300.000 × 25% × 2 × 52 × 30.000 ≈ **234 tỷ đồng/năm**.

Bước 6 — đọc chênh lệch: hai con số cách nhau ~8%. Với sizing, lệch dưới hai lần là **khớp**; lệch mười lần mới là dấu hiệu có nhân tử sai. Kết luận nộp đi phải là một khoảng: **200–260 tỷ đồng/năm**, kèm câu "giả định yếu nhất là 8 ly/giờ; nếu nó là 5 thì con số xuống còn ~160 tỷ".

Chú ý thứ tự: viết chuỗi → điền giả định → nhân → kiểm chéo → nêu giả định yếu nhất. Người mới thường nhảy thẳng vào bước nhân rồi không còn gì để nói khi bị hỏi vặn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.05', '019', 5, 'pitfall', 'Ba lỗi giết chết một bài bottom-up', '**SIZ-06 — lấy công suất tối đa làm sản lượng thực.** Quán có 20 chỗ ngồi không có nghĩa là lúc nào cũng đủ 20 khách. Máy chạy 24 giờ trên giấy tờ thì thực tế chạy 16. Sửa: luôn nhân công suất với một hệ số lấp đầy, và nói ra hệ số đó.

**SIZ-04 — quên tần suất.** Chuỗi chỉ có "số khách × giá" là chuỗi thiếu tầng ba: khách đó mua mấy lần một năm? Đây là lỗi làm con số lệch không phải vài phần trăm mà vài chục lần.

**SIZ-09 — kết thúc bằng đúng một con số.** Nộp "252 tỷ" mà không nói giả định nào yếu nhất là tự bỏ mất phần điểm dễ nhất, và là thứ người phỏng vấn hỏi ngay sau đó. Luôn kết bằng một khoảng cộng một câu về nhân tử nhạy nhất.

Nếu kết quả bottom-up và top-down của bạn lệch từ mười lần trở lên, đừng chọn đại một con số: đó là **SIZ-02**, và việc cần làm là dò lại từng nhân tử để tìm chỗ sai đơn vị.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.06', '019', 6, 'checklist', 'Trước khi nộp, soát 6 dòng', '- Chuỗi nhân tử được viết ra trước khi điền số, và có đủ ba tầng (đơn vị × sản lượng × tần suất).
- Mỗi giả định nằm trong ô riêng, có nhãn quan sát / suy ra / đoán.
- Đơn vị nhất quán: ngày với ngày, năm với năm, đồng với đồng.
- Có kết quả của cả hai cách, và một dòng giải thích chênh lệch.
- Kết quả làm tròn hợp lý (hai chữ số có nghĩa là đủ) và trình bày dưới dạng khoảng.
- Có câu "giả định yếu nhất là …, nếu nó sai thì con số thành …".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.07', '019', 7, 'exercise', 'Bài nộp', 'Chọn **một** trong ba thị trường sau, ước lượng doanh thu một năm bằng bottom-up, rồi kiểm chéo bằng top-down:

1. Dịch vụ rửa xe máy trong một quận.
2. Suất ăn trưa văn phòng giao tới một toà nhà 20 tầng.
3. Lốp xe tải thay mới trên một tuyến quốc lộ.

Giới hạn 25 phút. Không tra cứu: mục tiêu là chuỗi lập luận, không phải số liệu chính xác.

Output: một bảng tính có sheet `assumptions` (mỗi giả định một dòng, có nhãn A/B/C) và sheet `sizing` (chuỗi bottom-up, chuỗi top-down, chênh lệch tính bằng %, và một ô text ghi giả định yếu nhất).');
DELETE FROM lesson_blocks WHERE lesson_id = '101';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.01', '101', 1, 'goal', 'Checkpoint này kiểm tra gì', 'Đây là **cổng của module A1**: qua bài này thì các module phía sau mở ra, chưa qua thì dừng lại ở đây. Không phải để làm khó — mà vì mọi thứ sau này (issue tree, sizing, khuyến nghị) đều dựng trên câu hỏi bạn đã định khung. Định khung sai thì càng phân tích giỏi càng đi xa khỏi đích.

Trong 35 phút bạn nhận **ba đề case thô** và nộp: ba problem statement ba dòng, mỗi đề kèm bộ câu hỏi làm rõ có giải thích.

Bài này do giảng viên chấm, không phải bạn học chấm chéo.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.02', '101', 2, 'concept', 'Điều kiện đạt, nói trước cho rõ', 'Rubric chấm bốn tiêu chí, và có hai ngưỡng bạn nên biết trước khi làm:

- Tổng điểm phải từ **70** trở lên.
- **Không tiêu chí nào được ở mức 1.** Một bài trung bình khá ở mọi mặt sẽ qua; một bài xuất sắc ba phần nhưng hỏng hẳn một phần thì không. Định khung là việc mà một lỗ hổng đủ làm hỏng cả bài.

Bốn tiêu chí, kèm trọng số: câu hỏi chính đúng trọng tâm (30) · tiêu chí thành công định lượng (25) · scope hợp lý (20) · câu hỏi làm rõ có giá trị phân tích (25).

Ba đề sẽ có ít nhất một đề thuộc dạng "khách hàng đã tự chẩn đoán sẵn" — tức là đề mời bạn nhận luôn kết luận của họ. Đề đó là chỗ phân loại thật sự.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.03', '101', 3, 'concept', 'Ba mươi lăm phút chia thế nào', 'Người trượt checkpoint này thường không phải vì không biết làm, mà vì hết giờ ở đề thứ nhất. Cách chia thời gian dùng được:

1. **3 phút đọc cả ba đề** trước khi viết chữ nào. Đọc hết để biết đề nào dễ, làm đề dễ trước.
2. **8 phút mỗi đề** cho problem statement và câu hỏi làm rõ. Hết 8 phút thì chuyển, kể cả khi chưa ưng.
3. **8 phút cuối** quay lại: soát ba bài theo checklist, bổ sung số vào tiêu chí còn thiếu, cắt câu hỏi nào không qua được bộ lọc "nếu trả lời khác thì làm khác ở đâu".

Một bài gần xong ở cả ba đề luôn được điểm cao hơn một bài hoàn hảo ở đề đầu và bỏ trống hai đề sau — vì mức 1 ở bất kỳ tiêu chí nào cũng chặn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.04', '101', 4, 'worked_example', 'Hai bản cho cùng một đề, và vì sao một bản chỉ đạt mức 2', '**Đề thô:** Một trung tâm tiếng Anh 6 cơ sở, số học viên mới giảm 20% sau Tết. Ban giám đốc cho rằng do đối thủ giảm học phí và muốn biết nên giảm giá bao nhiêu để lấy lại học viên.

**Bản chỉ đạt mức 2:**

> *Câu hỏi:* Trung tâm nên giảm học phí bao nhiêu phần trăm để lấy lại 20% học viên đã mất?
> *Tiêu chí:* lấy lại số học viên như trước Tết.
> *Câu hỏi làm rõ:* Đối thủ giảm bao nhiêu? Học phí hiện tại? Có bao nhiêu cơ sở? Chương trình học thế nào? Giáo viên bao nhiêu người?

Vì sao trần mức 2: bản này **nhận nguyên chẩn đoán của khách hàng** rằng nguyên nhân là giá (FRM-04 ở dạng nhẹ), tiêu chí không có mốc thời gian và không có ràng buộc lợi nhuận, và ba trong năm câu hỏi không đổi được hướng phân tích (FRM-03).

**Bản đạt mức 3–4:**

> *Câu hỏi:* Vì sao số học viên mới giảm 20% sau Tết, và trong các cách phản ứng — giảm giá, đổi gói học, tăng chuyển đổi từ học thử — cách nào giữ được lợi nhuận tuyệt đối của năm nay?
> *Tiêu chí:* số học viên mới trở lại mức trước Tết trong 2 quý, đồng thời lợi nhuận gộp cả năm không thấp hơn năm ngoái.
> *Người quyết định và ràng buộc:* ban giám đốc; không sa thải giáo viên; ngân sách marketing giữ nguyên.
>
> *Câu hỏi làm rõ, mỗi câu kèm lý do:*
> 1. Học viên giảm ở cả 6 cơ sở hay tập trung vài cơ sở? — *cục bộ thì nguyên nhân là vận hành, không phải giá.*
> 2. Tỷ lệ chuyển đổi từ học thử sang đóng tiền thay đổi thế nào? — *nếu chuyển đổi giảm mà lượt học thử không giảm thì vấn đề nằm ở trải nghiệm, giảm giá không cứu được.*
> 3. Cùng kỳ năm ngoái sau Tết có giảm không? — *phân biệt mùa vụ với sự cố thật.*
> 4. Học viên rời đi nói lý do gì khi được hỏi? — *dữ liệu rẻ nhất và gần nguyên nhân nhất.*
> 5. Lợi nhuận trên một học viên hiện tại là bao nhiêu? — *quyết định biên độ giảm giá tối đa còn chịu được.*

Khác biệt không nằm ở chữ nghĩa mà ở một điểm: bản sau **chưa chấp nhận nguyên nhân do khách hàng đưa ra**, và năm câu hỏi của nó rải qua ba nhóm khác nhau (phân bố, phễu chuyển đổi, mùa vụ) thay vì năm câu cùng về giá.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.05', '101', 5, 'pitfall', 'Những gì thường làm trượt checkpoint này', '**FRM-04 — nhận chẩn đoán của đề bài.** Lỗi phổ biến nhất và tốn điểm nhất ở đây, vì nó kéo cả bốn tiêu chí xuống cùng lúc.

**FRM-02 — tiêu chí thiếu số hoặc thiếu mốc thời gian.** Dễ sửa nhất trong 8 phút cuối, nên đừng để mất điểm ở đây.

**FRM-03 — câu hỏi làm rõ không có lý do.** Ở checkpoint, câu hỏi **không kèm lý do** bị tính là câu hỏi không có tác dụng, kể cả khi bản thân câu hỏi hay.

**FRM-01 — ba problem statement na ná nhau.** Ba đề khác nhau mà ba câu hỏi chính viết cùng một khuôn là dấu hiệu bạn đang điền mẫu chứ không đang đọc đề.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.06', '101', 6, 'checklist', 'Soát trong 8 phút cuối', '- Ba đề đều có đủ ba dòng, không đề nào bỏ trống.
- Mỗi tiêu chí thành công có ít nhất một con số và một mốc thời gian.
- Mỗi câu hỏi làm rõ có một dòng lý do.
- Ít nhất một đề có tái định nghĩa rõ so với chẩn đoán trong đề gốc.
- Không có câu nào là giải pháp.
- Đọc lướt: ba câu hỏi chính khác nhau thật sự, không phải một khuôn ba lần.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('101.07', '101', 7, 'exercise', 'Bài nộp', 'Làm checkpoint trong **35 phút liên tục, không tạm dừng**. Không tra cứu, không hỏi ai — checkpoint đo cái bạn làm được một mình.

Nếu chưa đạt: bài sẽ bị khoá lại cho tới khi bạn xem phần nhận xét và viết lại phần sai. Đó không phải hình phạt — mã lỗi bạn dính ở đây sẽ quyết định drill nào được giao, và làm lại sau khi đã sửa đúng chỗ thì lần sau qua thật, không phải qua nhờ may.

Output: một tài liệu gồm ba phần (mỗi đề một phần), mỗi phần có problem statement ba dòng và bảng câu hỏi làm rõ hai cột (câu hỏi · lý do), cộng một dòng cuối bài tự đánh giá đề nào bạn thấy chắc nhất và vì sao.');
DELETE FROM lesson_blocks WHERE lesson_id = '103';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.01', '103', 1, 'goal', 'Checkpoint này kiểm tra gì', 'Cổng của module A3. Bạn nhận **một công ty chưa từng nghiên cứu** và có 40 phút để nộp: canvas một trang, ba đòn bẩy lợi nhuận xếp hạng có số, và một rủi ro thuộc về mô hình.

Điểm khác biệt so với bài teardown 011: ở đó bạn có hai mô hình để so sánh, so sánh làm lộ ra bản chất. Ở đây **chỉ có một công ty**, không có gì để đối chiếu — nên bạn phải tự dựng mốc so sánh. Đó chính là thứ checkpoint này đo.

Bài do giảng viên chấm. Đạt từ **70** điểm và **không tiêu chí nào ở mức 1**.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.02', '103', 2, 'concept', 'Bốn tiêu chí và trọng số, biết trước để phân bổ công sức', '| Tiêu chí | Trọng số | Nó hỏi gì |
|---|---|---|
| Dòng doanh thu đúng | 25 | Ai trả tiền, trả theo đơn vị nào, tiền vào trước hay sau khi phục vụ |
| Cấu trúc chi phí đúng | 25 | Chặng nào ăn bao nhiêu phần trăm, cái nào biến đổi, cái nào cố định |
| Đòn bẩy chọn đúng và giải thích được | 30 | Ba đòn bẩy xếp hạng, mỗi cái kèm ước lượng tác động |
| Nhận diện rủi ro mô hình | 20 | Rủi ro nằm trong cấu trúc kiếm tiền, không phải rủi ro chung chung |

Trọng số nói cho bạn biết nên tiêu thời gian ở đâu: **đòn bẩy nặng nhất (30)** nhưng lại là phần người học hay làm vội trong 5 phút cuối. Đảo lại thứ tự đó là cách dễ nhất để thêm điểm.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.03', '103', 3, 'concept', 'Không có mốc so sánh thì tự dựng lấy ba mốc', 'Khi chỉ có một công ty, "biên gộp 38%" tự nó không nói lên điều gì. Ba mốc dựng được ngay trong phòng thi, không cần tra cứu:

1. **So với chính nó theo thời gian.** Con số này năm ngoái thế nào? Nếu đề không cho, hỏi. Xu hướng nói nhiều hơn mức tuyệt đối — đây cũng là cách tránh **FIN-01**.
2. **So với cấu trúc lý thuyết của mô hình.** Mô hình sàn trung gian sống bằng mật độ; nếu công ty này có biên tốt nhưng mật độ thấp thì biên tốt đó là tạm thời.
3. **So với kịch bản xấu.** Doanh thu giảm 30% thì còn lại gì? Với công ty nặng chi phí cố định, câu trả lời thường đã đủ để viết phần rủi ro.

Ba mốc này hoạt động cả khi bạn chưa biết gì về ngành. Đừng đợi có số ngành mới dám kết luận — hãy nói rõ mốc mình đang dùng.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.04', '103', 4, 'concept', 'Bốn mươi phút chia thế nào', '- **5 phút — đọc và gọi tên mô hình.** Viết ra: đây là mô hình gì, nên chỉ số sống còn là gì. Cả bài sau đó xoay quanh câu này.
- **10 phút — canvas sáu ô.** Điền nhanh, chừa ô nào chưa rõ để hỏi, không ngồi nghĩ.
- **10 phút — dựng bảng kinh tế đơn vị.** Một đơn vị bán ra: thu bao nhiêu, chi bao nhiêu, còn bao nhiêu. Có số thì tính, không có số thì đặt giả định và ghi rõ.
- **10 phút — ba đòn bẩy.** Mỗi đòn bẩy phải có một phép nhân đi kèm; không có số thì chưa gọi là đòn bẩy.
- **5 phút — rủi ro mô hình và soát lại.**

Nếu đến phút 25 mà chưa có bảng kinh tế đơn vị, hãy bỏ bớt chi tiết ở canvas và đi tiếp. Canvas đẹp mà không có đòn bẩy chỉ lấy được 50 điểm trọng số; đòn bẩy tốt mà canvas sơ sài vẫn qua.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.05', '103', 5, 'worked_example', 'Teardown 40 phút cho một chuỗi rửa xe', '**Đề (rút gọn):** Chuỗi 5 điểm rửa xe máy và ô tô ở ngoại thành. Rửa xe máy 40.000đ, ô tô 120.000đ. Mỗi điểm trung bình 60 xe máy và 15 ô tô/ngày, mở 28 ngày/tháng. Mỗi điểm có 4 nhân viên lương 7 triệu/tháng, mặt bằng 25 triệu/tháng, nước và hoá chất khoảng 8.000đ/xe máy và 25.000đ/ô tô. Chuỗi vừa mua gói phần mềm quản lý 15 triệu/tháng cho cả chuỗi.

**Phút 0–5 — gọi tên mô hình:** bán đứt theo lượt dịch vụ, **nặng chi phí cố định** (nhân sự và mặt bằng cố định, doanh thu phụ thuộc lượt xe). → Chỉ số sống còn: **số lượt trên một điểm mỗi ngày**, tức công suất sử dụng.

**Phút 5–15 — canvas rút gọn:**

| Ô | Nội dung |
|---|---|
| Khách trả tiền | Chủ xe cá nhân, trả ngay sau dịch vụ |
| Đơn vị tính tiền | Một lượt rửa, hai mức giá theo loại xe |
| Chi phí một đơn vị | Nước + hoá chất: 8.000đ / 25.000đ |
| Chi phí dù không bán | Lương 28 triệu + mặt bằng 25 triệu mỗi điểm, phần mềm 15 triệu toàn chuỗi |
| Tiền vào trước hay sau | Sau khi phục vụ, không có công nợ — dòng tiền sạch |
| Cái gì chặn người khác làm giống | Gần như không có, trừ vị trí. **Đây là ô quan trọng nhất của đề này.** |

**Phút 15–25 — kinh tế một điểm mỗi tháng:**

- Doanh thu: (60 × 40.000 + 15 × 120.000) × 28 = (2.400.000 + 1.800.000) × 28 = **117,6 triệu**
- Biến đổi: (60 × 8.000 + 15 × 25.000) × 28 = (480.000 + 375.000) × 28 = **23,94 triệu** → biên gộp **79,6%**
- Cố định mỗi điểm: 28 + 25 = 53 triệu; phần mềm phân bổ 15 ÷ 5 = 3 triệu → **56 triệu**
- **Lợi nhuận mỗi điểm: 117,6 − 23,94 − 56 = 37,66 triệu/tháng**
- Hoà vốn: lãi gộp trung bình mỗi lượt = (4,2 triệu − 855.000) ÷ 75 lượt ≈ 44.600đ → cần 56.000.000 ÷ 44.600 ≈ **1.256 lượt/tháng ≈ 45 lượt/ngày**, bằng 60% mức hiện tại.

**Phút 25–35 — ba đòn bẩy, xếp hạng:**

1. **Tỷ trọng ô tô (43% doanh thu chỉ từ 20% số lượt).** Một lượt ô tô mang lãi gộp 95.000đ so với 32.000đ của xe máy. Chuyển 5 lượt xe máy/ngày thành 5 lượt ô tô: +8,8 triệu/tháng mỗi điểm. Cách làm: ưu tiên khung giờ, giá combo, tận dụng cầu nâng.
2. **Công suất giờ thấp điểm (cố định 56 triệu là 47,6% doanh thu).** Thêm 10 lượt xe máy/ngày ở khung vắng: +8,96 triệu/tháng, không tốn thêm chi phí cố định.
3. **Hoá chất và nước (20,4% doanh thu).** Giảm 10% định mức: +2,39 triệu/tháng. Nhỏ hơn hai đòn bẩy trên và có rủi ro rửa không sạch.

**Phút 35–40 — rủi ro mô hình:** ô số 6 trống — **không có gì chặn người khác mở điểm rửa xe ngay cạnh**. Với biên gộp 79,6% và vốn đầu tư thấp, ngành này mời gọi đối thủ. Dấu hiệu nhận biết sớm: số lượt mỗi điểm giảm trong khi tổng lượt toàn khu vực không giảm. Khi đó lợi nhuận 37,66 triệu/điểm sẽ bị chia sẻ rất nhanh, và vì chi phí cố định chiếm gần một nửa doanh thu, mất 25% lượt là gần hết lãi.

Chú ý cách viết rủi ro: nó đọc thẳng từ **cấu trúc** (biên cao + rào cản thấp + cố định nặng), không phải từ câu "thị trường cạnh tranh".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.06', '103', 6, 'pitfall', 'Những gì làm trượt checkpoint này', '**BIZ-02 — canvas đầy đủ nhưng không có đòn bẩy.** Mất trọn 30 điểm trọng số nặng nhất. Đây là kiểu trượt phổ biến nhất ở A3.

**BIZ-04 — giả định biên lợi nhuận không có cơ sở.** Viết "ngành này biên khoảng 30%" mà không neo vào dữ kiện nào trong đề. Nếu phải đoán, hãy đoán từ số có sẵn: giá bán trừ chi phí nguyên vật liệu đã cho.

**FIN-01 — đọc số tuyệt đối không so sánh.** "Lợi nhuận 37,66 triệu/tháng" không nói lên gì cho tới khi đặt cạnh vốn đầu tư, cạnh tháng trước, hoặc cạnh kịch bản xấu.

**REC-04 — impact ghi "tăng đáng kể".** Ở tiêu chí đòn bẩy, một đề xuất không có phép nhân đi kèm bị tính là chưa giải thích được, dù ý tưởng hay.

**Rủi ro chung chung.** "Cạnh tranh gay gắt", "kinh tế khó khăn" áp cho công ty nào cũng đúng, nên không nói gì về công ty này. Rủi ro mô hình phải chỉ được vào một ô cụ thể trong canvas.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.07', '103', 7, 'checklist', 'Soát trong 5 phút cuối', '- Canvas đủ sáu ô, ô rào cản không bỏ trống.
- Có bảng kinh tế một đơn vị với ít nhất một biên tính ra được.
- Ba đòn bẩy, mỗi cái có một phép nhân và một con số tiền.
- Đòn bẩy xếp hạng có lý do, không liệt kê ngang hàng.
- Rủi ro chỉ đích danh một ô trong canvas và có dấu hiệu nhận biết sớm.
- Mọi giả định tự đặt đều ghi rõ là giả định, kèm căn cứ suy ra.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('103.08', '103', 8, 'exercise', 'Bài nộp', 'Làm checkpoint trong **40 phút liên tục**, với một công ty do giảng viên phát — bạn sẽ gặp lần đầu ngay trong lúc làm. Không tra cứu.

Chưa đạt thì bài bị khoá cho tới khi bạn xem lại phần chấm và viết lại chỗ sai. Mã lỗi dính ở đây quyết định drill được giao, nên hãy đọc kỹ phần gắn mã hơn là nhìn điểm số.

Output: canvas sáu ô, bảng kinh tế một đơn vị (doanh thu · biến đổi · cố định · còn lại · hoà vốn), ba đòn bẩy xếp hạng có ước lượng bằng tiền, và một đoạn ngắn về rủi ro mô hình kèm dấu hiệu nhận biết sớm.');
DELETE FROM panel_questions WHERE case_id = 'C-040';
DELETE FROM case_answer_frames WHERE case_id = 'C-040';
DELETE FROM case_traps WHERE case_id = 'C-040';
DELETE FROM case_reveal_items WHERE case_id = 'C-040';
DELETE FROM cases WHERE id = 'C-040';
INSERT INTO cases (id, lesson_id, title, industry, context, question, duration_min, is_fictional, status, pilot_runs, version) VALUES ('C-040', '019', 'Chuỗi giặt sấy tự động muốn biết thị trường một quận to cỡ nào', 'Dịch vụ tiêu dùng', 'GiatNhanh là một chuỗi tiệm giặt sấy tự động hư cấu, đang có 6 tiệm ở một quận nội thành. Chủ chuỗi muốn biết quận này còn chỗ cho bao nhiêu tiệm nữa trước khi nghĩ tới việc mở sang quận khác, nên câu hỏi đầu tiên là thị trường giặt sấy tự động của riêng quận này một năm to cỡ nào.

Người phỏng vấn đóng vai chủ chuỗi. Người học được phép hỏi, nhưng mỗi câu hỏi phải nêu rõ mình cần con số đó để làm gì.', 'Ước lượng doanh thu giặt sấy tự động của toàn quận trong một năm, bằng bottom-up, và nói rõ giả định nào yếu nhất. Sau đó cho biết con số đó ủng hộ hay phản đối việc mở thêm tiệm.', 30, 1, 'draft', 0, 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r1', 'C-040', 'Phát sẵn', 'Quận có khoảng 300 nghìn dân, mật độ cao, nhiều nhà trọ và chung cư mini. GiatNhanh có 6 tiệm, mỗi tiệm 8 máy giặt và 4 máy sấy, mở cửa 6h–22h.', 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r2', 'C-040', 'Nếu hỏi số tiệm trong quận', 'Theo khảo sát tự làm của chủ chuỗi, cả quận có khoảng 45 tiệm giặt sấy tự động, tính cả 6 tiệm của GiatNhanh. Con số này chủ chuỗi đếm bằng cách đi một vòng, không phải số liệu chính thức.', 2);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r3', 'C-040', 'Nếu hỏi một máy chạy bao nhiêu lượt một ngày', 'Ở tiệm của GiatNhanh, máy giặt chạy trung bình 6 lượt/ngày tính cả ngày vắng; cao điểm cuối tuần lên 11 lượt, sáng thứ Ba có khi chỉ 2 lượt.', 3);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r4', 'C-040', 'Nếu hỏi giá một lượt', 'Giặt 40 nghìn một lượt, sấy 40 nghìn một lượt. Khoảng 70% khách giặt xong thì sấy luôn.', 4);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r5', 'C-040', 'Nếu hỏi tỷ lệ lấp đầy hoặc công suất tối đa', 'Nếu tính theo lý thuyết, một máy giặt chạy 45 phút một lượt, mở 16 tiếng thì được 21 lượt/ngày. Chủ chuỗi nói thẳng: "chưa bao giờ có ngày nào như thế."', 5);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r6', 'C-040', 'Nếu hỏi khách quay lại bao nhiêu lần', 'Khách quen dùng khoảng 1 lần/tuần. Chủ chuỗi không có số liệu về tổng số khách, chỉ có số lượt máy chạy.', 6);
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t1', 'C-040', 'Đề cố tình đặt sẵn con số công suất lý thuyết 21 lượt/ngày ngay cạnh con số thực 6 lượt/ngày. Người học vội sẽ nhân 45 tiệm × 12 máy × 21 lượt và ra một con số lớn gấp ba lần thực tế. Người làm đúng phải hỏi hoặc tự đặt hệ số lấp đầy, và nói ra hệ số đó.', 'SIZ-06');
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t2', 'C-040', 'Câu hỏi thứ hai ("ủng hộ hay phản đối mở thêm") chỉ trả lời được nếu người học đưa ra một khoảng và biết giả định nào lung lay. Ai kết thúc bằng đúng một con số sẽ không có gì để nói khi chủ chuỗi hỏi "anh chắc không".', 'SIZ-09');
INSERT INTO case_answer_frames (case_id, structure_md, key_numbers, quick_scoring_md) VALUES ('C-040', 'Chuỗi mong đợi: **số tiệm × số máy giặt mỗi tiệm × lượt/máy/ngày × 365 × giá lượt giặt**, rồi cộng phần sấy bằng cách nhân tỷ lệ 70%.

Bốn việc phải thấy trong bài làm:

1. Dùng lượt thực (6/ngày) chứ không dùng công suất lý thuyết (21/ngày); nếu dùng con số khác thì phải nói rõ hệ số lấp đầy.
2. Tách riêng doanh thu giặt và doanh thu sấy, vì giá bằng nhau nhưng tần suất khác nhau.
3. Kiểm chéo bằng top-down từ phía cầu: bao nhiêu hộ dùng dịch vụ, mỗi tuần mấy lượt.
4. Kết luận cho câu hỏi kinh doanh: 6/45 tiệm là khoảng 13% thị phần; muốn mở thêm thì phải nói mở để giành phần của ai, chứ thị trường không tự lớn ra.', '{"số tiệm toàn quận": 45, "máy giặt mỗi tiệm": 8, "lượt thực mỗi máy mỗi ngày": 6, "giá mỗi lượt (đồng)": 40000, "tỷ lệ khách sấy sau khi giặt": 0.7, "doanh thu giặt một năm (tỷ đồng)": 31.5, "doanh thu sấy một năm (tỷ đồng)": 22.1, "khoảng chấp nhận được (tỷ đồng)": "45–65", "thị phần GiatNhanh theo số tiệm": 0.13}', 'Chấm nhanh trong 3 phút:

- **Đạt (mức 3 trở lên):** ra khoảng 45–65 tỷ đồng/năm, có tách giặt và sấy, có nêu hệ số lấp đầy, có một câu về giả định yếu nhất.
- **Mức 2:** chuỗi đúng nhưng dùng thẳng công suất lý thuyết, hoặc quên phần sấy; con số rơi vào 100–200 tỷ.
- **Mức 1:** không viết chuỗi ra, nhảy thẳng vào số; hoặc kết thúc bằng một con số không có khoảng, không có giả định.
- Gắn **SIZ-06** nếu dùng 21 lượt/ngày mà không có hệ số; gắn **SIZ-09** nếu thiếu câu về giả định yếu nhất.

Lưu ý cho người chấm: con số cuối **không phải** tiêu chí chính. Một bài ra 48 tỷ bằng lập luận cẩu thả kém hơn một bài ra 70 tỷ mà chỉ ra được chính xác mình đã đoán ở đâu.');
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q10', 'C-040', 'numbers', 'Nếu lượt thực là 4 chứ không phải 6 thì con số của bạn thay đổi thế nào?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q11', 'C-040', 'numbers', 'Bạn lấy 45 tiệm ở đâu ra, và sai số của con số đó là bao nhiêu?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q20', 'C-040', 'feasibility', 'Mở thêm tiệm thứ 7 thì nó lấy khách của ai: của đối thủ hay của chính 6 tiệm đang có?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q21', 'C-040', 'feasibility', 'Cần bao nhiêu lượt/ngày thì một tiệm mới hoà vốn, và giả định nào của bạn quyết định con số đó?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q30', 'C-040', 'challenge', 'Một nửa số tiệm trong quận có thể đang lỗ. Điều đó thay đổi gì trong khuyến nghị của bạn?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q31', 'C-040', 'challenge', 'Nếu tôi nói khảo sát của tôi đếm thiếu một nửa số tiệm, kết luận của bạn còn đứng được không?', 0);
DELETE FROM rubric_criterion_levels WHERE criterion_id IN (SELECT id FROM rubric_criteria WHERE rubric_id = 'RM-A1');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.1', 1, 'Chép lại yêu cầu trong đề, hoặc viết một câu hỏi mà trả lời xong vẫn không ai ra quyết định được. Không có động từ quyết định.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.1', 2, 'Có câu hỏi quyết định rõ ràng nhưng giữ nguyên chẩn đoán của đề bài; không nhận ra dữ kiện trong đề đang mâu thuẫn với yêu cầu đó.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.1', 3, 'Tái định nghĩa được vấn đề: chỉ ra điều kiện phải kiểm trước khi trả lời yêu cầu gốc, và nêu được hệ quả nếu bỏ qua điều kiện đó.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.1', 4, 'Như mức 3, và câu hỏi được viết sao cho nhiều phương án cùng được xét chứ không chốt sẵn hướng; giữ nguyên mục tiêu của khách hàng thay vì bác bỏ nó.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.2', 1, 'Không có tiêu chí, hoặc tiêu chí chỉ là tính từ ("tăng trưởng tốt", "hiệu quả hơn").');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.2', 2, 'Có chỉ số nhưng thiếu ngưỡng hoặc thiếu mốc thời gian, nên không biết khi nào thì trả lời xong.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.2', 3, 'Đủ chỉ số, ngưỡng và mốc thời gian; ngưỡng do người học tự đặt thì có ghi rõ là giả định.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.2', 4, 'Như mức 3, và ngưỡng có căn cứ nêu ra được (mức hiện tại, mức đối thủ, hoặc mức tối thiểu để quyết định có nghĩa), kèm ràng buộc của người ra quyết định.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.3', 1, 'Không nêu phạm vi, hoặc phạm vi rộng tới mức không thể làm xong trong thời lượng của đề.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.3', 2, 'Có scope in nhưng không có scope out, hoặc scope out không kèm lý do.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.3', 3, 'Có cả hai chiều, mỗi dòng loại trừ kèm lý do hợp lệ; phạm vi vừa với thời lượng.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.3', 4, 'Như mức 3, và với dòng loại trừ rủi ro nhất có thêm một câu nói rõ kết luận sẽ đổi thế nào nếu loại nhầm.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.4', 1, 'Hỏi những thứ không đổi được hướng phân tích, hoặc hỏi lại thông tin đã có sẵn trong đề.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.4', 2, 'Có một vài câu đáng hỏi nhưng phần lớn dồn vào một nhóm, và không giải thích vì sao hỏi.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.4', 3, 'Mỗi câu kèm lý do "nếu trả lời khác thì tôi làm khác ở đâu"; câu hỏi rải qua ít nhất ba nhóm khác nhau; có câu về kinh tế một đơn vị.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A1.4', 4, 'Như mức 3, và có ít nhất một câu nhắm vào phân bố thay vì trung bình, hoặc vào "vì sao là bây giờ" — tức là câu hỏi có khả năng lật ngược chẩn đoán ban đầu.');
DELETE FROM rubric_criterion_levels WHERE criterion_id IN (SELECT id FROM rubric_criteria WHERE rubric_id = 'RM-A3');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.1', 1, 'Không nói được ai trả tiền hoặc tính tiền theo đơn vị nào; nhầm người dùng với người trả tiền khi hai bên khác nhau.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.1', 2, 'Nêu đúng nguồn doanh thu chính nhưng bỏ sót nguồn phụ, hoặc không nói được tiền vào trước hay sau khi phục vụ.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.1', 3, 'Đủ ba điều: ai trả, tính theo đơn vị nào, tiền vào lúc nào; nếu có nhiều nguồn thì tách riêng từng nguồn.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.1', 4, 'Như mức 3, và gọi đúng tên mô hình doanh thu rồi rút ra được chỉ số sống còn tương ứng của mô hình đó.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.2', 1, 'Liệt kê chi phí bằng số tuyệt đối, không quy về phần trăm doanh thu, hoặc trộn lẫn giá vốn với chi phí cố định.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.2', 2, 'Có tách các chặng chi phí nhưng không phân biệt biến đổi với cố định, nên không nói được điều gì xảy ra khi doanh thu thay đổi.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.2', 3, 'Mỗi chặng có phần trăm doanh thu và nhãn biến đổi hay cố định; tính được một biên (gộp hoặc hoạt động) đúng.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.2', 4, 'Như mức 3, và tính được điểm hoà vốn hoặc mô tả được kịch bản doanh thu giảm mạnh, chỉ ra chi phí nào không co lại theo.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.3', 1, 'Không có đòn bẩy, hoặc đề xuất chung chung kiểu "tăng marketing", "cải thiện dịch vụ", không gắn với dòng chi phí hay doanh thu nào.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.3', 2, 'Có ba đề xuất nhưng liệt kê ngang hàng, hoặc thiếu ước lượng tác động nên không biết cái nào đáng làm trước.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.3', 3, 'Ba đòn bẩy xếp hạng, mỗi cái gắn với một dòng cụ thể trong cấu trúc kinh tế và kèm một phép tính ra số tiền.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.3', 4, 'Như mức 3, và thứ tự xếp hạng có lý do rõ ràng theo tác động nhân với khả năng thực hiện; nêu được tác dụng phụ hoặc điều kiện kèm theo của đòn bẩy rủi ro nhất.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.4', 1, 'Không nêu rủi ro, hoặc chỉ nêu rủi ro áp cho doanh nghiệp nào cũng đúng như "cạnh tranh gay gắt", "kinh tế khó khăn".');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.4', 2, 'Rủi ro có liên quan tới doanh nghiệp này nhưng nằm ở vận hành hằng ngày chứ không nằm trong cách nó kiếm tiền.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.4', 3, 'Rủi ro chỉ đích danh một thành phần của mô hình — rào cản gia nhập, phụ thuộc một nguồn khách, cơ cấu chi phí cố định, thời điểm thu tiền.');
INSERT INTO rubric_criterion_levels (criterion_id, level, descriptor) VALUES ('RM-A3.4', 4, 'Như mức 3, và kèm dấu hiệu nhận biết sớm quan sát được, cộng ước lượng hệ quả nếu rủi ro xảy ra.');
