-- Generated by scripts/build-authored.py — do not edit; edit authoring/ instead.
DELETE FROM lesson_blocks WHERE lesson_id = '001';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.01', '001', 1, 'goal', 'Sau bài này bạn làm được gì', 'Đọc một đề case dài một trang và viết lại thành **problem statement ba dòng**: câu hỏi chính phải trả lời, tiêu chí biết là đã trả lời xong, và người ra quyết định là ai.

Không thuộc bài này: giải case, dựng issue tree, tính toán. Ở đây chỉ làm đúng một việc — **xác định câu hỏi**. Việc này chiếm chưa tới 5% thời gian làm case nhưng quyết định 100% phần còn lại đi đúng hay đi lạc.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.02', '001', 2, 'concept', 'Đề bài viết ra và câu hỏi thật sự hiếm khi trùng nhau', 'Đề case luôn được viết dưới góc nhìn của người trong cuộc, và người trong cuộc thường đã tự chẩn đoán sẵn. "Chúng tôi muốn biết nên mở thêm bao nhiêu cửa hàng" là một *giải pháp đã chọn*, không phải câu hỏi. Câu hỏi thật sự có thể là "mô hình cửa hàng hiện tại có đủ lành để nhân rộng không".

Ba dấu hiệu đề bài đang giấu câu hỏi thật:

- **Đề hỏi "làm thế nào" khi chưa ai trả lời "có nên không".** Hỏi mở ở đâu trong khi 4/12 cửa hàng đang lỗ là bỏ qua một bước.
- **Đề nêu một mục tiêu không có số.** "Tăng trưởng mạnh hơn" không kiểm chứng được, nên không trả lời được.
- **Đề đưa sẵn nguyên nhân.** "Doanh thu giảm vì đối thủ giảm giá" — đó là giả thuyết của khách hàng, phải kiểm chứ không phải nhận.

Việc của bạn không phải là bắt bẻ đề bài. Việc của bạn là **nói lại câu hỏi bằng ngôn ngữ kiểm chứng được**, rồi xác nhận với người ra quyết định trước khi phân tích.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.03', '001', 3, 'concept', 'Ba dòng của một problem statement', 'Dòng 1 — **Câu hỏi quyết định**: một câu, có động từ quyết định (có nên, chọn cái nào, bao nhiêu), có đối tượng cụ thể, có mốc thời gian.

Dòng 2 — **Tiêu chí thành công**: con số nào, đạt mức nào, trong bao lâu. Không có số ở dòng này thì cả bài không có đích.

Dòng 3 — **Người quyết định và ràng buộc**: ai sẽ dùng câu trả lời này, và họ bị chặn bởi cái gì (ngân sách, thời gian, năng lực, quy định).

Ba dòng, không hơn. Nếu bạn cần dòng thứ tư, gần như chắc chắn bạn đang viết phần phân tích chứ không còn viết đề nữa.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.04', '001', 4, 'worked_example', 'Từ một trang đề thành ba dòng', '**Đề (rút gọn):** Một chuỗi phòng tập 8 cơ sở tại TP.HCM, doanh thu ba năm đi ngang quanh 60 tỷ. Ban giám đốc thấy các chuỗi mới mở rất nhanh nên muốn biết "nên mở thêm bao nhiêu cơ sở trong 18 tháng tới và ở quận nào". Họ nói thêm: hai cơ sở mới nhất mở năm ngoái hiện chưa hoà vốn, và tỷ lệ hội viên bỏ tập sau 3 tháng là 45%.

**Bước 1 — gạch chân các dữ kiện không khớp với câu hỏi.** Hai cơ sở mới chưa hoà vốn; bỏ tập 45%. Cả hai đều nói rằng mô hình hiện tại đang rò rỉ. Mở thêm chỉ nhân bản chỗ rò rỉ đó.

**Bước 2 — hỏi "nếu trả lời đúng câu hỏi trong đề, ban giám đốc có ra quyết định tốt hơn không?"** Không. Họ sẽ mở thêm 5 cơ sở cùng kiểu và mất tiền nhanh hơn.

**Bước 3 — viết lại thành ba dòng:**

> **Câu hỏi:** Chuỗi có nên mở thêm cơ sở trong 18 tháng tới không, và nếu có thì điều kiện nào phải đạt trước khi mở cơ sở đầu tiên?
>
> **Tiêu chí thành công:** một cơ sở đạt hoà vốn trong vòng 9 tháng và giữ tỷ lệ bỏ tập sau 3 tháng dưới 30%; nếu hai điều kiện này chưa đạt ở các cơ sở hiện có thì câu trả lời là chưa mở.
>
> **Người quyết định và ràng buộc:** ban giám đốc, ngân sách đầu tư tối đa 20 tỷ trong 18 tháng, không tăng vay.

**Bước 4 — kiểm lại bằng ba câu hỏi:** Câu hỏi có động từ quyết định chưa? Có. Tiêu chí có số chưa? Có. Có nói ai quyết định chưa? Có.

Chú ý: bản viết lại **không** bác bỏ đề bài. Nó vẫn trả lời "mở bao nhiêu", chỉ đặt thêm điều kiện phải qua trước. Đó là cách định khung lại mà không biến mình thành người khó chịu trong phòng họp.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.05', '001', 5, 'pitfall', 'Bốn kiểu hỏng của problem statement', '**FRM-01 — nhắc lại đề thay vì định khung.** Viết "Chuỗi muốn biết nên mở thêm bao nhiêu cơ sở" là chép lại. Dấu hiệu: bỏ problem statement của bạn đi thì bài chẳng mất gì. Sửa: mỗi dòng phải thêm một thông tin không có trong đề — điều kiện, con số, ràng buộc.

**FRM-02 — mục tiêu không có số.** "Cải thiện lợi nhuận" không phải tiêu chí. Sửa: luôn có một con số và một mốc thời gian, kể cả khi con số đó là giả định của bạn — ghi rõ là giả định.

**FRM-04 — nhảy vào giải pháp ngay câu đầu.** "Chuỗi nên tập trung vào khách hàng doanh nghiệp" là kết luận, mà bạn chưa phân tích gì. Sửa: giai đoạn này chỉ được viết câu hỏi, không được viết câu trả lời.

**FRM-03 — hỏi làm rõ những thứ không đổi được hướng phân tích.** Hỏi "phòng tập mở cửa mấy giờ" trong khi chưa biết kinh tế một cơ sở ra sao là tiêu phí lượt hỏi. Trước mỗi câu hỏi, tự trả lời: *nếu đáp án là A thay vì B thì tôi sẽ làm khác đi ở chỗ nào?* Không trả lời được thì đừng hỏi.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.06', '001', 6, 'checklist', 'Soát trước khi nộp', '- Câu hỏi có động từ quyết định và mốc thời gian.
- Tiêu chí thành công có ít nhất một con số.
- Có tên người ra quyết định và ít nhất một ràng buộc.
- Ba dòng thêm được thông tin mà đề bài chưa nói.
- Không có câu nào là giải pháp hay kết luận.
- Đọc to lên trong 20 giây mà người nghe hiểu ngay đang giải bài gì.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('001.07', '001', 7, 'exercise', 'Bài nộp', 'Chọn một trong ba đề dưới đây, viết problem statement ba dòng trong **10 phút mỗi đề** (tổng 25 phút cho cả bài, gồm thời gian soát):

1. Một tiệm bánh có 3 chi nhánh muốn biết nên bán online hay mở thêm chi nhánh thứ 4.
2. Một trường ngoại ngữ thấy học viên đăng ký giảm 20% sau Tết và muốn biết nên giảm giá bao nhiêu.
3. Một công ty giao đồ ăn muốn biết nên vào thị trường Đà Nẵng trong quý tới hay không.

Với mỗi đề, ghi thêm **một câu** nói rõ bạn đã định khung lại chỗ nào so với đề gốc, và vì sao.

Output: một trang (docs hoặc markdown) gồm ba problem statement, mỗi cái đúng ba dòng, kèm một dòng "định khung lại" cho mỗi đề.');
DELETE FROM lesson_blocks WHERE lesson_id = '002';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.01', '002', 1, 'goal', 'Sau bài này bạn làm được gì', 'Viết lại một đề case thành **SCQ** — Situation, Complication, Question — để người nghe hiểu bối cảnh, hiểu vì sao bây giờ mới thành vấn đề, và biết chính xác câu hỏi đang cần trả lời, trong vòng 30 giây.

SCQ là bước ngay sau problem statement ở bài 001: problem statement là để **bạn** biết mình đang giải gì; SCQ là để **người nghe** chấp nhận rằng đó đúng là bài cần giải.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.02', '002', 2, 'concept', 'Ba phần, ba việc khác nhau', '**Situation** — những gì đúng và không ai tranh cãi. Đây là phần người nghe gật đầu. Chỉ gồm sự thật ổn định: quy mô, mô hình kinh doanh, vị trí hiện tại. Không có tính từ cảm xúc, không có nguyên nhân.

**Complication** — thứ vừa thay đổi và làm cho tình huống cũ không còn dùng được. Đây là phần khó nhất và cũng là phần phân biệt người viết giỏi: complication phải là một **sự thay đổi có thời điểm**, không phải một lời than. "Cạnh tranh gay gắt" là lời than. "Ba chuỗi mới vào thị trường trong 12 tháng qua, giá trung bình giảm 18%" là complication.

**Question** — câu hỏi quyết định, chính là dòng 1 của problem statement.

Kiểm tra nhanh một SCQ đạt: đọc xong Situation và Complication, người nghe **tự nghĩ ra** Question trước khi bạn nói. Nếu Question đến như một bất ngờ thì Complication chưa đúng.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.03', '002', 3, 'concept', 'Vì sao thứ tự này khó đảo', 'Người mới hay bắt đầu bằng câu hỏi ("Chúng ta cần quyết định có nên mở rộng không…") vì thấy nó vào thẳng vấn đề. Nhưng người nghe chưa có bối cảnh sẽ dành 30 giây tiếp theo để tự dựng lại bối cảnh trong đầu, và không nghe phần bạn đang nói.

Trật tự S → C → Q đặt người nghe vào đúng trạng thái: đồng ý → thấy có gì đó vừa gãy → cần một quyết định. Mỗi phần chuẩn bị cho phần sau. Đây cũng là bộ khung dùng lại được ở trang đầu tiên của deck và ở câu mở đầu khi thuyết trình.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.04', '002', 4, 'worked_example', 'Một đề, hai bản SCQ', '**Đề:** Một chuỗi trà sữa 15 cửa hàng, doanh thu 2 năm đi ngang 90 tỷ/năm, lợi nhuận gộp 55%. Năm ngoái chi phí mặt bằng tăng 12%, giao hàng qua app chiếm 40% đơn nhưng chiết khấu app là 25%. Chủ chuỗi hỏi có nên rút khỏi app không.

**Bản yếu:**

> *Situation:* Chuỗi trà sữa đang gặp khó khăn về lợi nhuận.
> *Complication:* Cạnh tranh ngày càng gay gắt và chi phí tăng.
> *Question:* Làm sao để tăng lợi nhuận?

Hỏng ở đâu: Situation đã cài sẵn kết luận ("gặp khó khăn"), Complication không có gì đo được, Question mơ hồ nên trả lời kiểu gì cũng được — tức là không trả lời được.

**Bản đạt:**

> *Situation:* Chuỗi có 15 cửa hàng, doanh thu ổn định 90 tỷ/năm, lợi nhuận gộp 55%. Kênh app chiếm 40% đơn hàng.
> *Complication:* Mỗi đơn qua app mất 25% chiết khấu, trong khi mặt bằng vừa tăng 12% trong 12 tháng qua. Với cơ cấu hiện tại, phần đơn tăng thêm từ app đang bào mòn lợi nhuận thay vì bù cho chi phí cố định.
> *Question:* Có nên giảm phụ thuộc vào app không, và nếu có thì giảm tới mức nào để tổng lợi nhuận năm sau không thấp hơn năm nay?

Đọc xong S và C, người nghe đã tự thấy câu hỏi trước khi tới dòng Q. Đó là dấu hiệu SCQ đạt.

Một chi tiết đáng học: bản đạt **không nói kênh app là xấu**. Nó nêu cơ cấu chi phí và để câu hỏi mở. Người viết chưa phân tích thì chưa được kết luận.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.05', '002', 5, 'pitfall', 'Ba lỗi hay gặp khi viết SCQ', '**FRM-01 — Situation chép lại đề.** Nếu Situation của bạn là ba câu đầu của đề bài viết gọn hơn, bạn chưa làm gì cả. Situation phải chọn lọc: chỉ giữ sự thật **cần thiết để hiểu Complication**, bỏ hết phần còn lại.

**FRM-02 — Complication không có số, không có mốc thời gian.** "Chi phí tăng" là trạng thái; "chi phí mặt bằng tăng 12% trong 12 tháng qua" là thay đổi. Chỉ thay đổi mới tạo ra nhu cầu quyết định.

**FRM-04 — Question thật ra là giải pháp.** "Có nên chuyển sang mô hình nhượng quyền không?" nghe như câu hỏi nhưng đã chốt sẵn hướng đi. Ở giai đoạn này, Question phải đủ rộng để nhiều phương án cùng được xét, và đủ hẹp để biết khi nào thì trả lời xong.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.06', '002', 6, 'checklist', 'Soát trước khi nộp', '- Situation chỉ chứa sự thật không ai tranh cãi, không có tính từ đánh giá.
- Complication có ít nhất một con số và một mốc thời gian.
- Người nghe đoán được Question sau khi nghe S và C.
- Question trùng với dòng 1 của problem statement, không mâu thuẫn.
- Cả ba phần đọc to trong 30 giây là hết.
- Không có câu nào kết luận thay cho phần phân tích chưa làm.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('002.07', '002', 7, 'exercise', 'Bài nộp', 'Viết SCQ cho **ba** đề sau, mỗi đề tối đa 8 phút:

1. Một nhà sách 12 chi nhánh, doanh thu đi ngang, muốn mở thêm 20 chi nhánh trong 24 tháng.
2. Một ứng dụng gọi xe thấy doanh thu giảm 12% một quý trong khi số chuyến không đổi.
3. Một nhà máy đồ gỗ xuất khẩu có đơn hàng tăng 30% nhưng lợi nhuận giảm.

Sau mỗi SCQ, viết một dòng: *"Complication của tôi là một thay đổi có thời điểm vì…"*. Nếu không viết nổi dòng đó, quay lại sửa Complication.

Output: một trang gồm ba SCQ, mỗi cái ba đoạn ngắn, kèm dòng tự kiểm Complication cho từng đề.');
DELETE FROM lesson_blocks WHERE lesson_id = '003';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.01', '003', 1, 'goal', 'Sau bài này bạn làm được gì', 'Viết **tiêu chí thành công đo được** cho một case, và một **bảng scope in / scope out** nói rõ cái gì bạn sẽ phân tích, cái gì cố ý không đụng tới, kèm lý do cho từng dòng loại trừ.

Đây là bài quyết định bạn có kết thúc case đúng giờ hay không. Case không bao giờ hết việc để làm; thứ duy nhất giúp bạn dừng đúng lúc là một đường biên đã vẽ sẵn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.02', '003', 2, 'concept', 'Tiêu chí thành công là điều kiện dừng, không phải lời hứa', 'Tiêu chí thành công trả lời câu: **khi nào thì tôi biết mình đã trả lời xong?** Nó luôn có ba phần:

1. **Chỉ số** — cái gì được đo. Lợi nhuận, thời gian hoàn vốn, thị phần, tỷ lệ giữ chân.
2. **Ngưỡng** — bao nhiêu thì đạt. Có con số, kể cả khi là giả định.
3. **Thời hạn** — trong bao lâu.

"Tăng lợi nhuận" thiếu cả ba. "Lợi nhuận trước thuế đạt 12 tỷ trong năm tài chính tới, tức tăng 20% so với năm nay" có đủ.

Khi khách hàng không đưa ngưỡng — trường hợp thường gặp — bạn tự đề xuất một ngưỡng và **ghi rõ đó là giả định của mình**, kèm căn cứ (mức hiện tại, mức của đối thủ, mức tối thiểu để dự án có nghĩa). Đề xuất một ngưỡng rồi kiểm chứng tốt hơn nhiều so với để trống.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.03', '003', 3, 'concept', 'Scope out mới là phần khó', 'Ai cũng viết được scope in. Giá trị nằm ở scope out, vì mỗi dòng loại trừ là một lời cam kết rằng bạn sẽ không tiêu thời gian vào đó.

Một dòng scope out đạt có hai vế: **loại trừ cái gì** và **vì sao loại được**. Lý do hợp lệ thường thuộc bốn nhóm:

- **Không đổi được kết luận** — dù đúng hay sai cũng không làm khuyến nghị khác đi.
- **Không quyết được trong phạm vi người ra quyết định** — ví dụ chính sách thuế.
- **Chi phí tìm hiểu lớn hơn giá trị** — dữ liệu phải mua, phải khảo sát nhiều tháng.
- **Đã có kết luận từ trước và không phải phần đang tranh cãi.**

Lý do không hợp lệ: "không đủ thời gian". Thời gian ít là ràng buộc chung; nó không giải thích vì sao *dòng này* bị cắt chứ không phải dòng khác.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.04', '003', 4, 'worked_example', 'Vẽ biên cho một case giao đồ ăn', '**Tình huống:** Một chuỗi cơm văn phòng 6 bếp muốn biết có nên tự xây đội giao hàng thay vì dùng app, trong 12 tháng tới. Bạn có 40 phút.

**Tiêu chí thành công:**

> Chi phí giao hàng trên mỗi đơn giảm xuống dưới 12.000đ và tỷ lệ giao đúng giờ giữ trên 92%, đạt được trong vòng 12 tháng, với vốn đầu tư ban đầu không quá 1,5 tỷ.
>
> *Giả định của tôi:* mức 12.000đ lấy từ chiết khấu app hiện tại (khoảng 22% trên đơn trung bình 55.000đ ≈ 12.100đ); 92% là mức đúng giờ hiện tại, không được phép tệ đi.

**Bảng scope:**

| Scope in | Vì sao cần |
|---|---|
| Kinh tế một đơn hàng: chi phí app hiện tại so với chi phí tự giao | Đây chính là phép so quyết định |
| Mật độ đơn theo khu vực và theo giờ | Quyết định số shipper và khả năng gộp đơn |
| Chi phí cố định của đội tự giao: lương, xe, bảo hiểm, điều phối | Phần app không thu nhưng tự làm thì phải chịu |
| Rủi ro mất đơn từ khách quen của app | Chi phí ẩn lớn nhất của việc rút khỏi app |

| Scope out | Vì sao loại được |
|---|---|
| Thiết kế app đặt hàng riêng | Không cần cho quyết định tự giao hay không; có thể dùng kênh đặt hàng hiện có |
| Mở thêm bếp mới | Là một quyết định khác, không đổi kết luận của bài này |
| Đàm phán lại chiết khấu với app | Đã đàm phán thất bại quý trước; không phải phần đang tranh cãi |
| Chính sách bảo hiểm cho tài xế công nghệ | Nằm ngoài quyền quyết định của chuỗi |

Đọc bảng này, người nghe biết chính xác 40 phút sẽ đi vào đâu — và quan trọng hơn, biết bạn **cố ý** không làm gì, thay vì tưởng bạn quên.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.05', '003', 5, 'pitfall', 'Ba lỗi làm mất tác dụng của scope', '**FRM-02 — tiêu chí không có ngưỡng.** "Giảm chi phí giao hàng" không có điểm dừng, nên bài sẽ trôi đến khi hết giờ. Sửa: đặt một con số, ghi rõ là giả định nếu chưa có dữ liệu.

**FRM-03 — hỏi làm rõ những thứ đã tự loại trừ.** Đã scope out mà vẫn tiêu lượt hỏi vào đó là tự mâu thuẫn, và người phỏng vấn sẽ nhận ra ngay. Sửa: sau khi vẽ biên, mọi câu hỏi làm rõ phải nằm trong scope in.

**FRM-04 — scope in viết như danh sách giải pháp.** "Tuyển 10 shipper" không phải phạm vi phân tích, đó là phương án. Scope in là *những câu hỏi con bạn sẽ trả lời*, không phải *những việc bạn sẽ khuyến nghị*.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.06', '003', 6, 'checklist', 'Soát trước khi nộp', '- Tiêu chí có đủ chỉ số, ngưỡng, thời hạn.
- Ngưỡng nào do bạn tự đặt thì có ghi "giả định" kèm căn cứ.
- Mỗi dòng scope out có lý do thuộc bốn nhóm hợp lệ, không có lý do "không đủ thời gian".
- Scope in là câu hỏi con, không phải giải pháp.
- Tổng số dòng scope in đủ nhỏ để làm xong trong thời lượng của case.
- Không có mục nào vừa nằm ở scope in vừa nằm ở scope out.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('003.07', '003', 7, 'exercise', 'Bài nộp', 'Lấy **một** đề bạn đã viết problem statement ở bài 001, dựng tiêu chí thành công và bảng scope trong 30 phút.

Yêu cầu tối thiểu: 4 dòng scope in, 4 dòng scope out, mỗi dòng scope out có lý do. Nếu một dòng loại trừ làm bạn thấy áy náy, giữ nó lại nhưng viết thêm một câu: *"nếu điều này sai thì kết luận thay đổi thế nào"* — đó là cách kiểm tra xem bạn có loại nhầm thứ quan trọng không.

Output: một bảng hai cột scope in / scope out (sheet hoặc markdown), phía trên là tiêu chí thành công ba phần, phía dưới là danh sách giả định bạn đã tự đặt.');
DELETE FROM lesson_blocks WHERE lesson_id = '019';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.01', '019', 1, 'goal', 'Sau bài này bạn làm được gì', 'Ước lượng quy mô một thị trường **từ dưới lên** — đi từ một đơn vị cung có thật (một cửa hàng, một xe, một nhân viên bán hàng) rồi nhân lên — và nói được vì sao con số của bạn lệch so với cách top-down.

Cụ thể, bạn sẽ nộp một bảng tính có: chuỗi nhân tử, ô giả định tách riêng, kết quả bottom-up, kết quả top-down, và một dòng giải thích chênh lệch.

Không thuộc bài này: chọn chiến lược thâm nhập, định giá, hay dự báo tăng trưởng nhiều năm. Ở đây chỉ có một câu hỏi: **thị trường này to cỡ nào, và tôi tin con số đó tới đâu**.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.02', '019', 2, 'concept', 'Bottom-up là đếm đơn vị cung, top-down là chia đơn vị cầu', 'Top-down bắt đầu từ một tổng lớn rồi cắt dần: dân số → nhóm tuổi → tỷ lệ dùng → chi tiêu mỗi người. Bottom-up bắt đầu từ một đơn vị bạn quan sát được rồi nhân lên: một cửa hàng bán bao nhiêu một ngày → bao nhiêu cửa hàng → bao nhiêu ngày mở cửa.

Chọn bottom-up khi:

- Bạn quan sát được đơn vị cung, hoặc đếm được nó trên bản đồ, trong báo cáo, ngoài đường.
- Đề hỏi về một phân khúc hẹp mà số tổng ngành không nói được gì (một quận, một kênh bán, một nhóm khách B2B).
- Bạn cần một con số **kiểm chứng chéo** cho kết quả top-down vừa tính.

Chọn top-down khi đơn vị cung quá phân mảnh để đếm, hoặc khi bạn chỉ có dữ liệu vĩ mô.

Câu quan trọng nhất của bài này: **hai cách không thay thế nhau, chúng kiểm tra nhau.** Một người làm case giỏi tính cả hai khi có thời gian, rồi dùng khoảng cách giữa hai kết quả để biết giả định nào của mình yếu nhất.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.03', '019', 3, 'concept', 'Chuỗi bottom-up luôn có ba tầng', 'Mọi chuỗi bottom-up dùng được đều có đúng ba loại nhân tử. Thiếu tầng nào là chuỗi sai ở đó:

1. **Số đơn vị** — bao nhiêu cửa hàng, xe, máy, nhân viên. Đây là tầng dễ đếm nhất và cũng dễ kiểm tra nhất.
2. **Sản lượng mỗi đơn vị mỗi lần** — một cửa hàng phục vụ bao nhiêu khách một giờ, một xe chở bao nhiêu chuyến.
3. **Tần suất** — bao nhiêu giờ hoạt động một ngày, bao nhiêu ngày một năm, khách quay lại mấy lần.

Viết chuỗi ra thành một hàng nhân tử trước khi điền số. Nếu không viết ra được hàng đó, bạn chưa hiểu thị trường chứ không phải thiếu dữ liệu.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.04', '019', 4, 'worked_example', 'Đếm ngược từ một quán cà phê', 'Đề: ước lượng doanh thu cà phê mang đi trong một quận nội thành, một năm.

Bước 1 — chọn đơn vị cung: một quán cà phê mang đi. Đếm được bằng cách đi một vòng vài con phố rồi suy ra mật độ.

Bước 2 — viết chuỗi trước khi điền số:

```
Doanh thu = số quán × ly/giờ × giờ mở/ngày × ngày/năm × giá/ly
```

Bước 3 — điền giả định, mỗi ô ghi rõ mình lấy ở đâu (A = quan sát, B = suy ra, C = đoán):

| Nhân tử | Giá trị | Loại | Ghi chú |
|---|---|---|---|
| Số quán trong quận | 250 | B | đếm 12 quán trên 3 phố, nhân theo số phố tương đương |
| Ly mỗi giờ (trung bình cả ngày) | 8 | C | giờ cao điểm ~20, thấp điểm ~3 |
| Giờ mở mỗi ngày | 12 | A | quan sát biển giờ mở cửa |
| Ngày mở mỗi năm | 350 | B | nghỉ Tết vài ngày |
| Giá mỗi ly | 30.000đ | A | bảng giá |

Bước 4 — nhân: 250 × 8 × 12 × 350 × 30.000 ≈ **252 tỷ đồng/năm**.

Bước 5 — kiểm tra chéo bằng top-down: quận có ~300 nghìn dân, giả sử 25% uống cà phê mua ngoài, trung bình 2 ly/tuần, 30.000đ/ly → 300.000 × 25% × 2 × 52 × 30.000 ≈ **234 tỷ đồng/năm**.

Bước 6 — đọc chênh lệch: hai con số cách nhau ~8%. Với sizing, lệch dưới hai lần là **khớp**; lệch mười lần mới là dấu hiệu có nhân tử sai. Kết luận nộp đi phải là một khoảng: **200–260 tỷ đồng/năm**, kèm câu "giả định yếu nhất là 8 ly/giờ; nếu nó là 5 thì con số xuống còn ~160 tỷ".

Chú ý thứ tự: viết chuỗi → điền giả định → nhân → kiểm chéo → nêu giả định yếu nhất. Người mới thường nhảy thẳng vào bước nhân rồi không còn gì để nói khi bị hỏi vặn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.05', '019', 5, 'pitfall', 'Ba lỗi giết chết một bài bottom-up', '**SIZ-06 — lấy công suất tối đa làm sản lượng thực.** Quán có 20 chỗ ngồi không có nghĩa là lúc nào cũng đủ 20 khách. Máy chạy 24 giờ trên giấy tờ thì thực tế chạy 16. Sửa: luôn nhân công suất với một hệ số lấp đầy, và nói ra hệ số đó.

**SIZ-04 — quên tần suất.** Chuỗi chỉ có "số khách × giá" là chuỗi thiếu tầng ba: khách đó mua mấy lần một năm? Đây là lỗi làm con số lệch không phải vài phần trăm mà vài chục lần.

**SIZ-09 — kết thúc bằng đúng một con số.** Nộp "252 tỷ" mà không nói giả định nào yếu nhất là tự bỏ mất phần điểm dễ nhất, và là thứ người phỏng vấn hỏi ngay sau đó. Luôn kết bằng một khoảng cộng một câu về nhân tử nhạy nhất.

Nếu kết quả bottom-up và top-down của bạn lệch từ mười lần trở lên, đừng chọn đại một con số: đó là **SIZ-02**, và việc cần làm là dò lại từng nhân tử để tìm chỗ sai đơn vị.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.06', '019', 6, 'checklist', 'Trước khi nộp, soát 6 dòng', '- Chuỗi nhân tử được viết ra trước khi điền số, và có đủ ba tầng (đơn vị × sản lượng × tần suất).
- Mỗi giả định nằm trong ô riêng, có nhãn quan sát / suy ra / đoán.
- Đơn vị nhất quán: ngày với ngày, năm với năm, đồng với đồng.
- Có kết quả của cả hai cách, và một dòng giải thích chênh lệch.
- Kết quả làm tròn hợp lý (hai chữ số có nghĩa là đủ) và trình bày dưới dạng khoảng.
- Có câu "giả định yếu nhất là …, nếu nó sai thì con số thành …".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.07', '019', 7, 'exercise', 'Bài nộp', 'Chọn **một** trong ba thị trường sau, ước lượng doanh thu một năm bằng bottom-up, rồi kiểm chéo bằng top-down:

1. Dịch vụ rửa xe máy trong một quận.
2. Suất ăn trưa văn phòng giao tới một toà nhà 20 tầng.
3. Lốp xe tải thay mới trên một tuyến quốc lộ.

Giới hạn 25 phút. Không tra cứu: mục tiêu là chuỗi lập luận, không phải số liệu chính xác.

Output: một bảng tính có sheet `assumptions` (mỗi giả định một dòng, có nhãn A/B/C) và sheet `sizing` (chuỗi bottom-up, chuỗi top-down, chênh lệch tính bằng %, và một ô text ghi giả định yếu nhất).');
DELETE FROM panel_questions WHERE case_id = 'C-040';
DELETE FROM case_answer_frames WHERE case_id = 'C-040';
DELETE FROM case_traps WHERE case_id = 'C-040';
DELETE FROM case_reveal_items WHERE case_id = 'C-040';
DELETE FROM cases WHERE id = 'C-040';
INSERT INTO cases (id, lesson_id, title, industry, context, question, duration_min, is_fictional, status, pilot_runs, version) VALUES ('C-040', '019', 'Chuỗi giặt sấy tự động muốn biết thị trường một quận to cỡ nào', 'Dịch vụ tiêu dùng', 'GiatNhanh là một chuỗi tiệm giặt sấy tự động hư cấu, đang có 6 tiệm ở một quận nội thành. Chủ chuỗi muốn biết quận này còn chỗ cho bao nhiêu tiệm nữa trước khi nghĩ tới việc mở sang quận khác, nên câu hỏi đầu tiên là thị trường giặt sấy tự động của riêng quận này một năm to cỡ nào.

Người phỏng vấn đóng vai chủ chuỗi. Người học được phép hỏi, nhưng mỗi câu hỏi phải nêu rõ mình cần con số đó để làm gì.', 'Ước lượng doanh thu giặt sấy tự động của toàn quận trong một năm, bằng bottom-up, và nói rõ giả định nào yếu nhất. Sau đó cho biết con số đó ủng hộ hay phản đối việc mở thêm tiệm.', 30, 1, 'draft', 0, 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r1', 'C-040', 'Phát sẵn', 'Quận có khoảng 300 nghìn dân, mật độ cao, nhiều nhà trọ và chung cư mini. GiatNhanh có 6 tiệm, mỗi tiệm 8 máy giặt và 4 máy sấy, mở cửa 6h–22h.', 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r2', 'C-040', 'Nếu hỏi số tiệm trong quận', 'Theo khảo sát tự làm của chủ chuỗi, cả quận có khoảng 45 tiệm giặt sấy tự động, tính cả 6 tiệm của GiatNhanh. Con số này chủ chuỗi đếm bằng cách đi một vòng, không phải số liệu chính thức.', 2);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r3', 'C-040', 'Nếu hỏi một máy chạy bao nhiêu lượt một ngày', 'Ở tiệm của GiatNhanh, máy giặt chạy trung bình 6 lượt/ngày tính cả ngày vắng; cao điểm cuối tuần lên 11 lượt, sáng thứ Ba có khi chỉ 2 lượt.', 3);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r4', 'C-040', 'Nếu hỏi giá một lượt', 'Giặt 40 nghìn một lượt, sấy 40 nghìn một lượt. Khoảng 70% khách giặt xong thì sấy luôn.', 4);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r5', 'C-040', 'Nếu hỏi tỷ lệ lấp đầy hoặc công suất tối đa', 'Nếu tính theo lý thuyết, một máy giặt chạy 45 phút một lượt, mở 16 tiếng thì được 21 lượt/ngày. Chủ chuỗi nói thẳng: "chưa bao giờ có ngày nào như thế."', 5);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r6', 'C-040', 'Nếu hỏi khách quay lại bao nhiêu lần', 'Khách quen dùng khoảng 1 lần/tuần. Chủ chuỗi không có số liệu về tổng số khách, chỉ có số lượt máy chạy.', 6);
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t1', 'C-040', 'Đề cố tình đặt sẵn con số công suất lý thuyết 21 lượt/ngày ngay cạnh con số thực 6 lượt/ngày. Người học vội sẽ nhân 45 tiệm × 12 máy × 21 lượt và ra một con số lớn gấp ba lần thực tế. Người làm đúng phải hỏi hoặc tự đặt hệ số lấp đầy, và nói ra hệ số đó.', 'SIZ-06');
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t2', 'C-040', 'Câu hỏi thứ hai ("ủng hộ hay phản đối mở thêm") chỉ trả lời được nếu người học đưa ra một khoảng và biết giả định nào lung lay. Ai kết thúc bằng đúng một con số sẽ không có gì để nói khi chủ chuỗi hỏi "anh chắc không".', 'SIZ-09');
INSERT INTO case_answer_frames (case_id, structure_md, key_numbers, quick_scoring_md) VALUES ('C-040', 'Chuỗi mong đợi: **số tiệm × số máy giặt mỗi tiệm × lượt/máy/ngày × 365 × giá lượt giặt**, rồi cộng phần sấy bằng cách nhân tỷ lệ 70%.

Bốn việc phải thấy trong bài làm:

1. Dùng lượt thực (6/ngày) chứ không dùng công suất lý thuyết (21/ngày); nếu dùng con số khác thì phải nói rõ hệ số lấp đầy.
2. Tách riêng doanh thu giặt và doanh thu sấy, vì giá bằng nhau nhưng tần suất khác nhau.
3. Kiểm chéo bằng top-down từ phía cầu: bao nhiêu hộ dùng dịch vụ, mỗi tuần mấy lượt.
4. Kết luận cho câu hỏi kinh doanh: 6/45 tiệm là khoảng 13% thị phần; muốn mở thêm thì phải nói mở để giành phần của ai, chứ thị trường không tự lớn ra.', '{"số tiệm toàn quận": 45, "máy giặt mỗi tiệm": 8, "lượt thực mỗi máy mỗi ngày": 6, "giá mỗi lượt (đồng)": 40000, "tỷ lệ khách sấy sau khi giặt": 0.7, "doanh thu giặt một năm (tỷ đồng)": 31.5, "doanh thu sấy một năm (tỷ đồng)": 22.1, "khoảng chấp nhận được (tỷ đồng)": "45–65", "thị phần GiatNhanh theo số tiệm": 0.13}', 'Chấm nhanh trong 3 phút:

- **Đạt (mức 3 trở lên):** ra khoảng 45–65 tỷ đồng/năm, có tách giặt và sấy, có nêu hệ số lấp đầy, có một câu về giả định yếu nhất.
- **Mức 2:** chuỗi đúng nhưng dùng thẳng công suất lý thuyết, hoặc quên phần sấy; con số rơi vào 100–200 tỷ.
- **Mức 1:** không viết chuỗi ra, nhảy thẳng vào số; hoặc kết thúc bằng một con số không có khoảng, không có giả định.
- Gắn **SIZ-06** nếu dùng 21 lượt/ngày mà không có hệ số; gắn **SIZ-09** nếu thiếu câu về giả định yếu nhất.

Lưu ý cho người chấm: con số cuối **không phải** tiêu chí chính. Một bài ra 48 tỷ bằng lập luận cẩu thả kém hơn một bài ra 70 tỷ mà chỉ ra được chính xác mình đã đoán ở đâu.');
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q10', 'C-040', 'numbers', 'Nếu lượt thực là 4 chứ không phải 6 thì con số của bạn thay đổi thế nào?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q11', 'C-040', 'numbers', 'Bạn lấy 45 tiệm ở đâu ra, và sai số của con số đó là bao nhiêu?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q20', 'C-040', 'feasibility', 'Mở thêm tiệm thứ 7 thì nó lấy khách của ai: của đối thủ hay của chính 6 tiệm đang có?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q21', 'C-040', 'feasibility', 'Cần bao nhiêu lượt/ngày thì một tiệm mới hoà vốn, và giả định nào của bạn quyết định con số đó?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q30', 'C-040', 'challenge', 'Một nửa số tiệm trong quận có thể đang lỗ. Điều đó thay đổi gì trong khuyến nghị của bạn?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q31', 'C-040', 'challenge', 'Nếu tôi nói khảo sát của tôi đếm thiếu một nửa số tiệm, kết luận của bạn còn đứng được không?', 0);
