-- Generated by scripts/build-authored.py — do not edit; edit authoring/ instead.
DELETE FROM lesson_blocks WHERE lesson_id = '019';
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.01', '019', 1, 'goal', 'Sau bài này bạn làm được gì', 'Ước lượng quy mô một thị trường **từ dưới lên** — đi từ một đơn vị cung có thật (một cửa hàng, một xe, một nhân viên bán hàng) rồi nhân lên — và nói được vì sao con số của bạn lệch so với cách top-down.

Cụ thể, bạn sẽ nộp một bảng tính có: chuỗi nhân tử, ô giả định tách riêng, kết quả bottom-up, kết quả top-down, và một dòng giải thích chênh lệch.

Không thuộc bài này: chọn chiến lược thâm nhập, định giá, hay dự báo tăng trưởng nhiều năm. Ở đây chỉ có một câu hỏi: **thị trường này to cỡ nào, và tôi tin con số đó tới đâu**.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.02', '019', 2, 'concept', 'Bottom-up là đếm đơn vị cung, top-down là chia đơn vị cầu', 'Top-down bắt đầu từ một tổng lớn rồi cắt dần: dân số → nhóm tuổi → tỷ lệ dùng → chi tiêu mỗi người. Bottom-up bắt đầu từ một đơn vị bạn quan sát được rồi nhân lên: một cửa hàng bán bao nhiêu một ngày → bao nhiêu cửa hàng → bao nhiêu ngày mở cửa.

Chọn bottom-up khi:

- Bạn quan sát được đơn vị cung, hoặc đếm được nó trên bản đồ, trong báo cáo, ngoài đường.
- Đề hỏi về một phân khúc hẹp mà số tổng ngành không nói được gì (một quận, một kênh bán, một nhóm khách B2B).
- Bạn cần một con số **kiểm chứng chéo** cho kết quả top-down vừa tính.

Chọn top-down khi đơn vị cung quá phân mảnh để đếm, hoặc khi bạn chỉ có dữ liệu vĩ mô.

Câu quan trọng nhất của bài này: **hai cách không thay thế nhau, chúng kiểm tra nhau.** Một người làm case giỏi tính cả hai khi có thời gian, rồi dùng khoảng cách giữa hai kết quả để biết giả định nào của mình yếu nhất.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.03', '019', 3, 'concept', 'Chuỗi bottom-up luôn có ba tầng', 'Mọi chuỗi bottom-up dùng được đều có đúng ba loại nhân tử. Thiếu tầng nào là chuỗi sai ở đó:

1. **Số đơn vị** — bao nhiêu cửa hàng, xe, máy, nhân viên. Đây là tầng dễ đếm nhất và cũng dễ kiểm tra nhất.
2. **Sản lượng mỗi đơn vị mỗi lần** — một cửa hàng phục vụ bao nhiêu khách một giờ, một xe chở bao nhiêu chuyến.
3. **Tần suất** — bao nhiêu giờ hoạt động một ngày, bao nhiêu ngày một năm, khách quay lại mấy lần.

Viết chuỗi ra thành một hàng nhân tử trước khi điền số. Nếu không viết ra được hàng đó, bạn chưa hiểu thị trường chứ không phải thiếu dữ liệu.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.04', '019', 4, 'worked_example', 'Đếm ngược từ một quán cà phê', 'Đề: ước lượng doanh thu cà phê mang đi trong một quận nội thành, một năm.

Bước 1 — chọn đơn vị cung: một quán cà phê mang đi. Đếm được bằng cách đi một vòng vài con phố rồi suy ra mật độ.

Bước 2 — viết chuỗi trước khi điền số:

```
Doanh thu = số quán × ly/giờ × giờ mở/ngày × ngày/năm × giá/ly
```

Bước 3 — điền giả định, mỗi ô ghi rõ mình lấy ở đâu (A = quan sát, B = suy ra, C = đoán):

| Nhân tử | Giá trị | Loại | Ghi chú |
|---|---|---|---|
| Số quán trong quận | 250 | B | đếm 12 quán trên 3 phố, nhân theo số phố tương đương |
| Ly mỗi giờ (trung bình cả ngày) | 8 | C | giờ cao điểm ~20, thấp điểm ~3 |
| Giờ mở mỗi ngày | 12 | A | quan sát biển giờ mở cửa |
| Ngày mở mỗi năm | 350 | B | nghỉ Tết vài ngày |
| Giá mỗi ly | 30.000đ | A | bảng giá |

Bước 4 — nhân: 250 × 8 × 12 × 350 × 30.000 ≈ **252 tỷ đồng/năm**.

Bước 5 — kiểm tra chéo bằng top-down: quận có ~300 nghìn dân, giả sử 25% uống cà phê mua ngoài, trung bình 2 ly/tuần, 30.000đ/ly → 300.000 × 25% × 2 × 52 × 30.000 ≈ **234 tỷ đồng/năm**.

Bước 6 — đọc chênh lệch: hai con số cách nhau ~8%. Với sizing, lệch dưới hai lần là **khớp**; lệch mười lần mới là dấu hiệu có nhân tử sai. Kết luận nộp đi phải là một khoảng: **200–260 tỷ đồng/năm**, kèm câu "giả định yếu nhất là 8 ly/giờ; nếu nó là 5 thì con số xuống còn ~160 tỷ".

Chú ý thứ tự: viết chuỗi → điền giả định → nhân → kiểm chéo → nêu giả định yếu nhất. Người mới thường nhảy thẳng vào bước nhân rồi không còn gì để nói khi bị hỏi vặn.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.05', '019', 5, 'pitfall', 'Ba lỗi giết chết một bài bottom-up', '**SIZ-06 — lấy công suất tối đa làm sản lượng thực.** Quán có 20 chỗ ngồi không có nghĩa là lúc nào cũng đủ 20 khách. Máy chạy 24 giờ trên giấy tờ thì thực tế chạy 16. Sửa: luôn nhân công suất với một hệ số lấp đầy, và nói ra hệ số đó.

**SIZ-04 — quên tần suất.** Chuỗi chỉ có "số khách × giá" là chuỗi thiếu tầng ba: khách đó mua mấy lần một năm? Đây là lỗi làm con số lệch không phải vài phần trăm mà vài chục lần.

**SIZ-09 — kết thúc bằng đúng một con số.** Nộp "252 tỷ" mà không nói giả định nào yếu nhất là tự bỏ mất phần điểm dễ nhất, và là thứ người phỏng vấn hỏi ngay sau đó. Luôn kết bằng một khoảng cộng một câu về nhân tử nhạy nhất.

Nếu kết quả bottom-up và top-down của bạn lệch từ mười lần trở lên, đừng chọn đại một con số: đó là **SIZ-02**, và việc cần làm là dò lại từng nhân tử để tìm chỗ sai đơn vị.');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.06', '019', 6, 'checklist', 'Trước khi nộp, soát 6 dòng', '- Chuỗi nhân tử được viết ra trước khi điền số, và có đủ ba tầng (đơn vị × sản lượng × tần suất).
- Mỗi giả định nằm trong ô riêng, có nhãn quan sát / suy ra / đoán.
- Đơn vị nhất quán: ngày với ngày, năm với năm, đồng với đồng.
- Có kết quả của cả hai cách, và một dòng giải thích chênh lệch.
- Kết quả làm tròn hợp lý (hai chữ số có nghĩa là đủ) và trình bày dưới dạng khoảng.
- Có câu "giả định yếu nhất là …, nếu nó sai thì con số thành …".');
INSERT INTO lesson_blocks (id, lesson_id, sort, kind, title, body_md) VALUES ('019.07', '019', 7, 'exercise', 'Bài nộp', 'Chọn **một** trong ba thị trường sau, ước lượng doanh thu một năm bằng bottom-up, rồi kiểm chéo bằng top-down:

1. Dịch vụ rửa xe máy trong một quận.
2. Suất ăn trưa văn phòng giao tới một toà nhà 20 tầng.
3. Lốp xe tải thay mới trên một tuyến quốc lộ.

Giới hạn 25 phút. Không tra cứu: mục tiêu là chuỗi lập luận, không phải số liệu chính xác.

Output: một bảng tính có sheet `assumptions` (mỗi giả định một dòng, có nhãn A/B/C) và sheet `sizing` (chuỗi bottom-up, chuỗi top-down, chênh lệch tính bằng %, và một ô text ghi giả định yếu nhất).');
DELETE FROM panel_questions WHERE case_id = 'C-040';
DELETE FROM case_answer_frames WHERE case_id = 'C-040';
DELETE FROM case_traps WHERE case_id = 'C-040';
DELETE FROM case_reveal_items WHERE case_id = 'C-040';
DELETE FROM cases WHERE id = 'C-040';
INSERT INTO cases (id, lesson_id, title, industry, context, question, duration_min, is_fictional, status, pilot_runs, version) VALUES ('C-040', '019', 'Chuỗi giặt sấy tự động muốn biết thị trường một quận to cỡ nào', 'Dịch vụ tiêu dùng', 'GiatNhanh là một chuỗi tiệm giặt sấy tự động hư cấu, đang có 6 tiệm ở một quận nội thành. Chủ chuỗi muốn biết quận này còn chỗ cho bao nhiêu tiệm nữa trước khi nghĩ tới việc mở sang quận khác, nên câu hỏi đầu tiên là thị trường giặt sấy tự động của riêng quận này một năm to cỡ nào.

Người phỏng vấn đóng vai chủ chuỗi. Người học được phép hỏi, nhưng mỗi câu hỏi phải nêu rõ mình cần con số đó để làm gì.', 'Ước lượng doanh thu giặt sấy tự động của toàn quận trong một năm, bằng bottom-up, và nói rõ giả định nào yếu nhất. Sau đó cho biết con số đó ủng hộ hay phản đối việc mở thêm tiệm.', 30, 1, 'draft', 0, 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r1', 'C-040', 'Phát sẵn', 'Quận có khoảng 300 nghìn dân, mật độ cao, nhiều nhà trọ và chung cư mini. GiatNhanh có 6 tiệm, mỗi tiệm 8 máy giặt và 4 máy sấy, mở cửa 6h–22h.', 1);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r2', 'C-040', 'Nếu hỏi số tiệm trong quận', 'Theo khảo sát tự làm của chủ chuỗi, cả quận có khoảng 45 tiệm giặt sấy tự động, tính cả 6 tiệm của GiatNhanh. Con số này chủ chuỗi đếm bằng cách đi một vòng, không phải số liệu chính thức.', 2);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r3', 'C-040', 'Nếu hỏi một máy chạy bao nhiêu lượt một ngày', 'Ở tiệm của GiatNhanh, máy giặt chạy trung bình 6 lượt/ngày tính cả ngày vắng; cao điểm cuối tuần lên 11 lượt, sáng thứ Ba có khi chỉ 2 lượt.', 3);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r4', 'C-040', 'Nếu hỏi giá một lượt', 'Giặt 40 nghìn một lượt, sấy 40 nghìn một lượt. Khoảng 70% khách giặt xong thì sấy luôn.', 4);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r5', 'C-040', 'Nếu hỏi tỷ lệ lấp đầy hoặc công suất tối đa', 'Nếu tính theo lý thuyết, một máy giặt chạy 45 phút một lượt, mở 16 tiếng thì được 21 lượt/ngày. Chủ chuỗi nói thẳng: "chưa bao giờ có ngày nào như thế."', 5);
INSERT INTO case_reveal_items (id, case_id, trigger, content, sort) VALUES ('C-040.r6', 'C-040', 'Nếu hỏi khách quay lại bao nhiêu lần', 'Khách quen dùng khoảng 1 lần/tuần. Chủ chuỗi không có số liệu về tổng số khách, chỉ có số lượt máy chạy.', 6);
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t1', 'C-040', 'Đề cố tình đặt sẵn con số công suất lý thuyết 21 lượt/ngày ngay cạnh con số thực 6 lượt/ngày. Người học vội sẽ nhân 45 tiệm × 12 máy × 21 lượt và ra một con số lớn gấp ba lần thực tế. Người làm đúng phải hỏi hoặc tự đặt hệ số lấp đầy, và nói ra hệ số đó.', 'SIZ-06');
INSERT INTO case_traps (id, case_id, description, mistake_code) VALUES ('C-040.t2', 'C-040', 'Câu hỏi thứ hai ("ủng hộ hay phản đối mở thêm") chỉ trả lời được nếu người học đưa ra một khoảng và biết giả định nào lung lay. Ai kết thúc bằng đúng một con số sẽ không có gì để nói khi chủ chuỗi hỏi "anh chắc không".', 'SIZ-09');
INSERT INTO case_answer_frames (case_id, structure_md, key_numbers, quick_scoring_md) VALUES ('C-040', 'Chuỗi mong đợi: **số tiệm × số máy giặt mỗi tiệm × lượt/máy/ngày × 365 × giá lượt giặt**, rồi cộng phần sấy bằng cách nhân tỷ lệ 70%.

Bốn việc phải thấy trong bài làm:

1. Dùng lượt thực (6/ngày) chứ không dùng công suất lý thuyết (21/ngày); nếu dùng con số khác thì phải nói rõ hệ số lấp đầy.
2. Tách riêng doanh thu giặt và doanh thu sấy, vì giá bằng nhau nhưng tần suất khác nhau.
3. Kiểm chéo bằng top-down từ phía cầu: bao nhiêu hộ dùng dịch vụ, mỗi tuần mấy lượt.
4. Kết luận cho câu hỏi kinh doanh: 6/45 tiệm là khoảng 13% thị phần; muốn mở thêm thì phải nói mở để giành phần của ai, chứ thị trường không tự lớn ra.', '{"số tiệm toàn quận": 45, "máy giặt mỗi tiệm": 8, "lượt thực mỗi máy mỗi ngày": 6, "giá mỗi lượt (đồng)": 40000, "tỷ lệ khách sấy sau khi giặt": 0.7, "doanh thu giặt một năm (tỷ đồng)": 31.5, "doanh thu sấy một năm (tỷ đồng)": 22.1, "khoảng chấp nhận được (tỷ đồng)": "45–65", "thị phần GiatNhanh theo số tiệm": 0.13}', 'Chấm nhanh trong 3 phút:

- **Đạt (mức 3 trở lên):** ra khoảng 45–65 tỷ đồng/năm, có tách giặt và sấy, có nêu hệ số lấp đầy, có một câu về giả định yếu nhất.
- **Mức 2:** chuỗi đúng nhưng dùng thẳng công suất lý thuyết, hoặc quên phần sấy; con số rơi vào 100–200 tỷ.
- **Mức 1:** không viết chuỗi ra, nhảy thẳng vào số; hoặc kết thúc bằng một con số không có khoảng, không có giả định.
- Gắn **SIZ-06** nếu dùng 21 lượt/ngày mà không có hệ số; gắn **SIZ-09** nếu thiếu câu về giả định yếu nhất.

Lưu ý cho người chấm: con số cuối **không phải** tiêu chí chính. Một bài ra 48 tỷ bằng lập luận cẩu thả kém hơn một bài ra 70 tỷ mà chỉ ra được chính xác mình đã đoán ở đâu.');
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q10', 'C-040', 'numbers', 'Nếu lượt thực là 4 chứ không phải 6 thì con số của bạn thay đổi thế nào?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q11', 'C-040', 'numbers', 'Bạn lấy 45 tiệm ở đâu ra, và sai số của con số đó là bao nhiêu?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q20', 'C-040', 'feasibility', 'Mở thêm tiệm thứ 7 thì nó lấy khách của ai: của đối thủ hay của chính 6 tiệm đang có?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q21', 'C-040', 'feasibility', 'Cần bao nhiêu lượt/ngày thì một tiệm mới hoà vốn, và giả định nào của bạn quyết định con số đó?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q30', 'C-040', 'challenge', 'Một nửa số tiệm trong quận có thể đang lỗ. Điều đó thay đổi gì trong khuyến nghị của bạn?', 0);
INSERT INTO panel_questions (id, case_id, category, text, from_appendix) VALUES ('C-040.q31', 'C-040', 'challenge', 'Nếu tôi nói khảo sát của tôi đếm thiếu một nửa số tiệm, kết luận của bạn còn đứng được không?', 0);
